// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
  user_id, name, industry, company_size, website, logo_url, description,
  headquarters, founded_year
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, name, industry, company_size, website, logo_url, description, headquarters, founded_year, is_verified, is_active, approved_by, approved_at, created_at, updated_at
`

type CreateCompanyParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	Name         string         `json:"name"`
	Industry     sql.NullString `json:"industry"`
	CompanySize  sql.NullString `json:"company_size"`
	Website      sql.NullString `json:"website"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Description  sql.NullString `json:"description"`
	Headquarters sql.NullString `json:"headquarters"`
	FoundedYear  sql.NullInt32  `json:"founded_year"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany,
		arg.UserID,
		arg.Name,
		arg.Industry,
		arg.CompanySize,
		arg.Website,
		arg.LogoUrl,
		arg.Description,
		arg.Headquarters,
		arg.FoundedYear,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Industry,
		&i.CompanySize,
		&i.Website,
		&i.LogoUrl,
		&i.Description,
		&i.Headquarters,
		&i.FoundedYear,
		&i.IsVerified,
		&i.IsActive,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, user_id, name, industry, company_size, website, logo_url, description, headquarters, founded_year, is_verified, is_active, approved_by, approved_at, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Industry,
		&i.CompanySize,
		&i.Website,
		&i.LogoUrl,
		&i.Description,
		&i.Headquarters,
		&i.FoundedYear,
		&i.IsVerified,
		&i.IsActive,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyByUserID = `-- name: GetCompanyByUserID :one
SELECT id, user_id, name, industry, company_size, website, logo_url, description, headquarters, founded_year, is_verified, is_active, approved_by, approved_at, created_at, updated_at FROM companies WHERE user_id = $1
`

func (q *Queries) GetCompanyByUserID(ctx context.Context, userID uuid.UUID) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByUserID, userID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Industry,
		&i.CompanySize,
		&i.Website,
		&i.LogoUrl,
		&i.Description,
		&i.Headquarters,
		&i.FoundedYear,
		&i.IsVerified,
		&i.IsActive,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, user_id, name, industry, company_size, website, logo_url, description, headquarters, founded_year, is_verified, is_active, approved_by, approved_at, created_at, updated_at FROM companies WHERE is_active = true ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListCompaniesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Industry,
			&i.CompanySize,
			&i.Website,
			&i.LogoUrl,
			&i.Description,
			&i.Headquarters,
			&i.FoundedYear,
			&i.IsVerified,
			&i.IsActive,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies SET 
  name = $2, industry = $3, company_size = $4, website = $5, logo_url = $6,
  description = $7, headquarters = $8, founded_year = $9, updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, name, industry, company_size, website, logo_url, description, headquarters, founded_year, is_verified, is_active, approved_by, approved_at, created_at, updated_at
`

type UpdateCompanyParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Industry     sql.NullString `json:"industry"`
	CompanySize  sql.NullString `json:"company_size"`
	Website      sql.NullString `json:"website"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Description  sql.NullString `json:"description"`
	Headquarters sql.NullString `json:"headquarters"`
	FoundedYear  sql.NullInt32  `json:"founded_year"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Industry,
		arg.CompanySize,
		arg.Website,
		arg.LogoUrl,
		arg.Description,
		arg.Headquarters,
		arg.FoundedYear,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Industry,
		&i.CompanySize,
		&i.Website,
		&i.LogoUrl,
		&i.Description,
		&i.Headquarters,
		&i.FoundedYear,
		&i.IsVerified,
		&i.IsActive,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
