// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCompanyJob = `-- name: CreateCompanyJob :one
INSERT INTO company_jobs (
  company_id, title, description, requirements, responsibilities, location,
  job_type, experience_min, experience_max, salary_min, salary_max,
  salary_currency, skills, benefits, application_url, application_email,
  is_remote, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, company_id, title, description, requirements, responsibilities, location, job_type, experience_min, experience_max, salary_min, salary_max, salary_currency, skills, benefits, application_url, application_email, is_remote, is_active, views_count, applications_count, posted_at, expires_at, created_at, updated_at
`

type CreateCompanyJobParams struct {
	CompanyID        uuid.UUID      `json:"company_id"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Requirements     sql.NullString `json:"requirements"`
	Responsibilities sql.NullString `json:"responsibilities"`
	Location         sql.NullString `json:"location"`
	JobType          sql.NullString `json:"job_type"`
	ExperienceMin    sql.NullInt32  `json:"experience_min"`
	ExperienceMax    sql.NullInt32  `json:"experience_max"`
	SalaryMin        sql.NullInt32  `json:"salary_min"`
	SalaryMax        sql.NullInt32  `json:"salary_max"`
	SalaryCurrency   sql.NullString `json:"salary_currency"`
	Skills           []string       `json:"skills"`
	Benefits         []string       `json:"benefits"`
	ApplicationUrl   sql.NullString `json:"application_url"`
	ApplicationEmail sql.NullString `json:"application_email"`
	IsRemote         sql.NullBool   `json:"is_remote"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateCompanyJob(ctx context.Context, arg CreateCompanyJobParams) (CompanyJob, error) {
	row := q.db.QueryRowContext(ctx, createCompanyJob,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.Requirements,
		arg.Responsibilities,
		arg.Location,
		arg.JobType,
		arg.ExperienceMin,
		arg.ExperienceMax,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
		pq.Array(arg.Skills),
		pq.Array(arg.Benefits),
		arg.ApplicationUrl,
		arg.ApplicationEmail,
		arg.IsRemote,
		arg.ExpiresAt,
	)
	var i CompanyJob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Location,
		&i.JobType,
		&i.ExperienceMin,
		&i.ExperienceMax,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		pq.Array(&i.Skills),
		pq.Array(&i.Benefits),
		&i.ApplicationUrl,
		&i.ApplicationEmail,
		&i.IsRemote,
		&i.IsActive,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompanyJob = `-- name: DeleteCompanyJob :exec
UPDATE company_jobs SET is_active = false WHERE id = $1
`

func (q *Queries) DeleteCompanyJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCompanyJob, id)
	return err
}

const getCompanyJobByID = `-- name: GetCompanyJobByID :one
SELECT id, company_id, title, description, requirements, responsibilities, location, job_type, experience_min, experience_max, salary_min, salary_max, salary_currency, skills, benefits, application_url, application_email, is_remote, is_active, views_count, applications_count, posted_at, expires_at, created_at, updated_at FROM company_jobs WHERE id = $1
`

func (q *Queries) GetCompanyJobByID(ctx context.Context, id uuid.UUID) (CompanyJob, error) {
	row := q.db.QueryRowContext(ctx, getCompanyJobByID, id)
	var i CompanyJob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Location,
		&i.JobType,
		&i.ExperienceMin,
		&i.ExperienceMax,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		pq.Array(&i.Skills),
		pq.Array(&i.Benefits),
		&i.ApplicationUrl,
		&i.ApplicationEmail,
		&i.IsRemote,
		&i.IsActive,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyJobsByCompanyID = `-- name: GetCompanyJobsByCompanyID :many
SELECT id, company_id, title, description, requirements, responsibilities, location, job_type, experience_min, experience_max, salary_min, salary_max, salary_currency, skills, benefits, application_url, application_email, is_remote, is_active, views_count, applications_count, posted_at, expires_at, created_at, updated_at FROM company_jobs WHERE company_id = $1 AND is_active = true ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetCompanyJobsByCompanyIDParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetCompanyJobsByCompanyID(ctx context.Context, arg GetCompanyJobsByCompanyIDParams) ([]CompanyJob, error) {
	rows, err := q.db.QueryContext(ctx, getCompanyJobsByCompanyID, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyJob
	for rows.Next() {
		var i CompanyJob
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Responsibilities,
			&i.Location,
			&i.JobType,
			&i.ExperienceMin,
			&i.ExperienceMax,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			pq.Array(&i.Skills),
			pq.Array(&i.Benefits),
			&i.ApplicationUrl,
			&i.ApplicationEmail,
			&i.IsRemote,
			&i.IsActive,
			&i.ViewsCount,
			&i.ApplicationsCount,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementJobViews = `-- name: IncrementJobViews :exec
UPDATE company_jobs SET views_count = views_count + 1 WHERE id = $1
`

func (q *Queries) IncrementJobViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementJobViews, id)
	return err
}

const listActiveCompanyJobs = `-- name: ListActiveCompanyJobs :many
SELECT id, company_id, title, description, requirements, responsibilities, location, job_type, experience_min, experience_max, salary_min, salary_max, salary_currency, skills, benefits, application_url, application_email, is_remote, is_active, views_count, applications_count, posted_at, expires_at, created_at, updated_at FROM company_jobs WHERE is_active = true
  AND ($1::text = '' OR location ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR job_type = $2)
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListActiveCompanyJobsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListActiveCompanyJobs(ctx context.Context, arg ListActiveCompanyJobsParams) ([]CompanyJob, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCompanyJobs,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyJob
	for rows.Next() {
		var i CompanyJob
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Requirements,
			&i.Responsibilities,
			&i.Location,
			&i.JobType,
			&i.ExperienceMin,
			&i.ExperienceMax,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			pq.Array(&i.Skills),
			pq.Array(&i.Benefits),
			&i.ApplicationUrl,
			&i.ApplicationEmail,
			&i.IsRemote,
			&i.IsActive,
			&i.ViewsCount,
			&i.ApplicationsCount,
			&i.PostedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyJob = `-- name: UpdateCompanyJob :one
UPDATE company_jobs SET
  title = $2, description = $3, requirements = $4, responsibilities = $5, location = $6,
  job_type = $7, experience_min = $8, experience_max = $9, salary_min = $10, salary_max = $11,
  salary_currency = $12, skills = $13, benefits = $14, application_url = $15, application_email = $16,
  is_remote = $17, expires_at = $18, updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, title, description, requirements, responsibilities, location, job_type, experience_min, experience_max, salary_min, salary_max, salary_currency, skills, benefits, application_url, application_email, is_remote, is_active, views_count, applications_count, posted_at, expires_at, created_at, updated_at
`

type UpdateCompanyJobParams struct {
	ID               uuid.UUID      `json:"id"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Requirements     sql.NullString `json:"requirements"`
	Responsibilities sql.NullString `json:"responsibilities"`
	Location         sql.NullString `json:"location"`
	JobType          sql.NullString `json:"job_type"`
	ExperienceMin    sql.NullInt32  `json:"experience_min"`
	ExperienceMax    sql.NullInt32  `json:"experience_max"`
	SalaryMin        sql.NullInt32  `json:"salary_min"`
	SalaryMax        sql.NullInt32  `json:"salary_max"`
	SalaryCurrency   sql.NullString `json:"salary_currency"`
	Skills           []string       `json:"skills"`
	Benefits         []string       `json:"benefits"`
	ApplicationUrl   sql.NullString `json:"application_url"`
	ApplicationEmail sql.NullString `json:"application_email"`
	IsRemote         sql.NullBool   `json:"is_remote"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
}

func (q *Queries) UpdateCompanyJob(ctx context.Context, arg UpdateCompanyJobParams) (CompanyJob, error) {
	row := q.db.QueryRowContext(ctx, updateCompanyJob,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Requirements,
		arg.Responsibilities,
		arg.Location,
		arg.JobType,
		arg.ExperienceMin,
		arg.ExperienceMax,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
		pq.Array(arg.Skills),
		pq.Array(arg.Benefits),
		arg.ApplicationUrl,
		arg.ApplicationEmail,
		arg.IsRemote,
		arg.ExpiresAt,
	)
	var i CompanyJob
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Location,
		&i.JobType,
		&i.ExperienceMin,
		&i.ExperienceMax,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		pq.Array(&i.Skills),
		pq.Array(&i.Benefits),
		&i.ApplicationUrl,
		&i.ApplicationEmail,
		&i.IsRemote,
		&i.IsActive,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.PostedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
