// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, channel, channel_id, title, url, thumbnail, 
       description, video_id, published_at, duration, 
       view_count, like_count, category, created_at
FROM youtube_videos 
WHERE id = $1 AND is_active = true
`

type GetVideoByIDRow struct {
	ID          uuid.UUID      `json:"id"`
	Channel     string         `json:"channel"`
	ChannelID   sql.NullString `json:"channel_id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Thumbnail   sql.NullString `json:"thumbnail"`
	Description sql.NullString `json:"description"`
	VideoID     string         `json:"video_id"`
	PublishedAt sql.NullTime   `json:"published_at"`
	Duration    sql.NullString `json:"duration"`
	ViewCount   sql.NullInt64  `json:"view_count"`
	LikeCount   sql.NullInt64  `json:"like_count"`
	Category    sql.NullString `json:"category"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetVideoByID(ctx context.Context, id uuid.UUID) (GetVideoByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVideoByID, id)
	var i GetVideoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ChannelID,
		&i.Title,
		&i.Url,
		&i.Thumbnail,
		&i.Description,
		&i.VideoID,
		&i.PublishedAt,
		&i.Duration,
		&i.ViewCount,
		&i.LikeCount,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getVideos = `-- name: GetVideos :many
SELECT id, channel, channel_id, title, url, thumbnail, 
       description, video_id, published_at, duration, 
       view_count, like_count, category, created_at
FROM youtube_videos 
WHERE is_active = true
  AND ($1::text = '' OR channel ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR category = $2)
ORDER BY published_at DESC 
LIMIT $3 OFFSET $4
`

type GetVideosParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetVideosRow struct {
	ID          uuid.UUID      `json:"id"`
	Channel     string         `json:"channel"`
	ChannelID   sql.NullString `json:"channel_id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Thumbnail   sql.NullString `json:"thumbnail"`
	Description sql.NullString `json:"description"`
	VideoID     string         `json:"video_id"`
	PublishedAt sql.NullTime   `json:"published_at"`
	Duration    sql.NullString `json:"duration"`
	ViewCount   sql.NullInt64  `json:"view_count"`
	LikeCount   sql.NullInt64  `json:"like_count"`
	Category    sql.NullString `json:"category"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetVideos(ctx context.Context, arg GetVideosParams) ([]GetVideosRow, error) {
	rows, err := q.db.QueryContext(ctx, getVideos,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVideosRow
	for rows.Next() {
		var i GetVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.ChannelID,
			&i.Title,
			&i.Url,
			&i.Thumbnail,
			&i.Description,
			&i.VideoID,
			&i.PublishedAt,
			&i.Duration,
			&i.ViewCount,
			&i.LikeCount,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosCount = `-- name: GetVideosCount :one
SELECT COUNT(*) FROM youtube_videos WHERE is_active = true
  AND ($1::text = '' OR channel ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR category = $2)
`

type GetVideosCountParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) GetVideosCount(ctx context.Context, arg GetVideosCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVideosCount, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}
