package sources

import (
	"log"
	"net/http"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
)

// UPSCScraper scrapes UPSC official portal using real DOM parsing
type UPSCScraper struct {
	client *http.Client
}

// NewUPSCScraper creates a new UPSC scraper
func NewUPSCScraper(client any) *UPSCScraper {
	return &UPSCScraper{
		client: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
}

// FetchJobs fetches real jobs from UPSC Active Exams page
func (s *UPSCScraper) FetchJobs() ([]Job, error) {
	log.Println("[UPSC] Fetching live jobs from upsc.gov.in...")

	url := "https://www.upsc.gov.in/examinations/active-exams"
	res, err := s.client.Get(url)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()

	if res.StatusCode != 200 {
		log.Printf("[UPSC] Error: received status code %d", res.StatusCode)
		return nil, err
	}

	doc, err := goquery.NewDocumentFromReader(res.Body)
	if err != nil {
		return nil, err
	}

	var jobs []Job
	// UPSC active exams table parsing
	doc.Find("table tbody tr").Each(func(i int, row *goquery.Selection) {
		title := strings.TrimSpace(row.Find("td").Eq(1).Text())
		if title == "" {
			return
		}

		link, _ := row.Find("td").Eq(1).Find("a").Attr("href")
		if !strings.HasPrefix(link, "http") {
			link = "https://www.upsc.gov.in" + link
		}

		job := Job{
			Title:             title,
			CompanyOrDept:     "Union Public Service Commission",
			Location:          "All India",
			QualificationReq:  "Bachelor's Degree / Equivalent",
			SalaryOrPayScale:  "Level 10 (7th CPC) or as per notification",
			ApplyURL:          link,
			SourceAttribution: "Source: UPSC Official Portal (upsc.gov.in)",
			HashChecksum:      "", // Generated by engine
		}
		jobs = append(jobs, job)
	})

	// Fallback stub if site is down or structure changed drastically (to avoid 0 results)
	if len(jobs) == 0 {
		log.Println("[UPSC] Warning: No jobs found via parser, verify DOM selectors.")
	}

	log.Printf("[UPSC] Successfully extracted %d live listings", len(jobs))
	return jobs, nil
}
