// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const applyJob = `-- name: ApplyJob :one
INSERT INTO job_applications (job_id, candidate_id, cover_letter, resume_url)
VALUES ($1, $2, $3, $4) RETURNING id, job_id, candidate_id, status, cover_letter, resume_url, match_score, notes, applied_at, updated_at
`

type ApplyJobParams struct {
	JobID       uuid.UUID      `json:"job_id"`
	CandidateID uuid.UUID      `json:"candidate_id"`
	CoverLetter sql.NullString `json:"cover_letter"`
	ResumeUrl   sql.NullString `json:"resume_url"`
}

func (q *Queries) ApplyJob(ctx context.Context, arg ApplyJobParams) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, applyJob,
		arg.JobID,
		arg.CandidateID,
		arg.CoverLetter,
		arg.ResumeUrl,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CandidateID,
		&i.Status,
		&i.CoverLetter,
		&i.ResumeUrl,
		&i.MatchScore,
		&i.Notes,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJobApplication = `-- name: CreateJobApplication :one
INSERT INTO job_applications (job_id, candidate_id, cover_letter, resume_url)
VALUES ($1, $2, $3, $4) RETURNING id, job_id, candidate_id, status, cover_letter, resume_url, match_score, notes, applied_at, updated_at
`

type CreateJobApplicationParams struct {
	JobID       uuid.UUID      `json:"job_id"`
	CandidateID uuid.UUID      `json:"candidate_id"`
	CoverLetter sql.NullString `json:"cover_letter"`
	ResumeUrl   sql.NullString `json:"resume_url"`
}

func (q *Queries) CreateJobApplication(ctx context.Context, arg CreateJobApplicationParams) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, createJobApplication,
		arg.JobID,
		arg.CandidateID,
		arg.CoverLetter,
		arg.ResumeUrl,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CandidateID,
		&i.Status,
		&i.CoverLetter,
		&i.ResumeUrl,
		&i.MatchScore,
		&i.Notes,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationWithDetails = `-- name: GetApplicationWithDetails :one
SELECT ja.id, ja.job_id, ja.candidate_id, ja.status, ja.cover_letter, ja.resume_url, ja.match_score, ja.notes, ja.applied_at, ja.updated_at, u.email, u.name as candidate_name, cj.title as job_title, co.name as company_name
FROM job_applications ja
JOIN candidates c ON ja.candidate_id = c.id
JOIN users u ON c.user_id = u.id
JOIN company_jobs cj ON ja.job_id = cj.id
JOIN companies co ON cj.company_id = co.id
WHERE ja.id = $1
`

type GetApplicationWithDetailsRow struct {
	ID            uuid.UUID       `json:"id"`
	JobID         uuid.UUID       `json:"job_id"`
	CandidateID   uuid.UUID       `json:"candidate_id"`
	Status        sql.NullString  `json:"status"`
	CoverLetter   sql.NullString  `json:"cover_letter"`
	ResumeUrl     sql.NullString  `json:"resume_url"`
	MatchScore    sql.NullFloat64 `json:"match_score"`
	Notes         sql.NullString  `json:"notes"`
	AppliedAt     sql.NullTime    `json:"applied_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
	Email         string          `json:"email"`
	CandidateName string          `json:"candidate_name"`
	JobTitle      string          `json:"job_title"`
	CompanyName   string          `json:"company_name"`
}

func (q *Queries) GetApplicationWithDetails(ctx context.Context, id uuid.UUID) (GetApplicationWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getApplicationWithDetails, id)
	var i GetApplicationWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CandidateID,
		&i.Status,
		&i.CoverLetter,
		&i.ResumeUrl,
		&i.MatchScore,
		&i.Notes,
		&i.AppliedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.CandidateName,
		&i.JobTitle,
		&i.CompanyName,
	)
	return i, err
}

const getJobApplicationByID = `-- name: GetJobApplicationByID :one
SELECT id, job_id, candidate_id, status, cover_letter, resume_url, match_score, notes, applied_at, updated_at FROM job_applications WHERE id = $1
`

func (q *Queries) GetJobApplicationByID(ctx context.Context, id uuid.UUID) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, getJobApplicationByID, id)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CandidateID,
		&i.Status,
		&i.CoverLetter,
		&i.ResumeUrl,
		&i.MatchScore,
		&i.Notes,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobApplicationsCountByJobID = `-- name: GetJobApplicationsCountByJobID :one
SELECT COUNT(*) FROM job_applications WHERE job_id = $1
`

func (q *Queries) GetJobApplicationsCountByJobID(ctx context.Context, jobID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getJobApplicationsCountByJobID, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listJobApplicationsByCandidateID = `-- name: ListJobApplicationsByCandidateID :many
SELECT id, job_id, candidate_id, status, cover_letter, resume_url, match_score, notes, applied_at, updated_at FROM job_applications WHERE candidate_id = $1 ORDER BY applied_at DESC LIMIT $2 OFFSET $3
`

type ListJobApplicationsByCandidateIDParams struct {
	CandidateID uuid.UUID `json:"candidate_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListJobApplicationsByCandidateID(ctx context.Context, arg ListJobApplicationsByCandidateIDParams) ([]JobApplication, error) {
	rows, err := q.db.QueryContext(ctx, listJobApplicationsByCandidateID, arg.CandidateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApplication
	for rows.Next() {
		var i JobApplication
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CandidateID,
			&i.Status,
			&i.CoverLetter,
			&i.ResumeUrl,
			&i.MatchScore,
			&i.Notes,
			&i.AppliedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobApplicationsByJobID = `-- name: ListJobApplicationsByJobID :many
SELECT id, job_id, candidate_id, status, cover_letter, resume_url, match_score, notes, applied_at, updated_at FROM job_applications WHERE job_id = $1 ORDER BY applied_at DESC LIMIT $2 OFFSET $3
`

type ListJobApplicationsByJobIDParams struct {
	JobID  uuid.UUID `json:"job_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListJobApplicationsByJobID(ctx context.Context, arg ListJobApplicationsByJobIDParams) ([]JobApplication, error) {
	rows, err := q.db.QueryContext(ctx, listJobApplicationsByJobID, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApplication
	for rows.Next() {
		var i JobApplication
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CandidateID,
			&i.Status,
			&i.CoverLetter,
			&i.ResumeUrl,
			&i.MatchScore,
			&i.Notes,
			&i.AppliedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobApplicationStatus = `-- name: UpdateJobApplicationStatus :one
UPDATE job_applications SET status = $2, notes = $3, updated_at = NOW() WHERE id = $1 RETURNING id, job_id, candidate_id, status, cover_letter, resume_url, match_score, notes, applied_at, updated_at
`

type UpdateJobApplicationStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
	Notes  sql.NullString `json:"notes"`
}

func (q *Queries) UpdateJobApplicationStatus(ctx context.Context, arg UpdateJobApplicationStatusParams) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, updateJobApplicationStatus, arg.ID, arg.Status, arg.Notes)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CandidateID,
		&i.Status,
		&i.CoverLetter,
		&i.ResumeUrl,
		&i.MatchScore,
		&i.Notes,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}
