// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_queue.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const enqueueEmail = `-- name: EnqueueEmail :one
INSERT INTO email_queue (to_email, subject, body)
VALUES ($1, $2, $3)
RETURNING id, to_email, subject, body, status, attempts, last_attempt_at, sent_at, error_message, created_at
`

type EnqueueEmailParams struct {
	ToEmail string `json:"to_email"`
	Subject string `json:"subject"`
	Body    string `json:"body"`
}

func (q *Queries) EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) (EmailQueue, error) {
	row := q.db.QueryRowContext(ctx, enqueueEmail, arg.ToEmail, arg.Subject, arg.Body)
	var i EmailQueue
	err := row.Scan(
		&i.ID,
		&i.ToEmail,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingEmails = `-- name: GetPendingEmails :many
SELECT id, to_email, subject, body, status, attempts, last_attempt_at, sent_at, error_message, created_at FROM email_queue
WHERE status = 'pending' AND attempts < 3
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingEmails(ctx context.Context, limit int32) ([]EmailQueue, error) {
	rows, err := q.db.QueryContext(ctx, getPendingEmails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailQueue
	for rows.Next() {
		var i EmailQueue
		if err := rows.Scan(
			&i.ID,
			&i.ToEmail,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.SentAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailStatus = `-- name: UpdateEmailStatus :one
UPDATE email_queue
SET status = $2, attempts = attempts + 1, last_attempt_at = NOW(), sent_at = CASE WHEN $2 = 'sent' THEN NOW() ELSE sent_at END, error_message = $3
WHERE id = $1
RETURNING id, to_email, subject, body, status, attempts, last_attempt_at, sent_at, error_message, created_at
`

type UpdateEmailStatusParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateEmailStatus(ctx context.Context, arg UpdateEmailStatusParams) (EmailQueue, error) {
	row := q.db.QueryRowContext(ctx, updateEmailStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i EmailQueue
	err := row.Scan(
		&i.ID,
		&i.ToEmail,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.SentAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}
