// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_uploads.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFileUpload = `-- name: CreateFileUpload :one
INSERT INTO file_uploads (user_id, file_type, file_url, original_name, file_size)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, file_type, file_url, original_name, file_size, created_at
`

type CreateFileUploadParams struct {
	UserID       uuid.UUID     `json:"user_id"`
	FileType     string        `json:"file_type"`
	FileUrl      string        `json:"file_url"`
	OriginalName string        `json:"original_name"`
	FileSize     sql.NullInt64 `json:"file_size"`
}

func (q *Queries) CreateFileUpload(ctx context.Context, arg CreateFileUploadParams) (FileUpload, error) {
	row := q.db.QueryRowContext(ctx, createFileUpload,
		arg.UserID,
		arg.FileType,
		arg.FileUrl,
		arg.OriginalName,
		arg.FileSize,
	)
	var i FileUpload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileType,
		&i.FileUrl,
		&i.OriginalName,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFileUpload = `-- name: DeleteFileUpload :exec
DELETE FROM file_uploads WHERE id = $1 AND user_id = $2
`

type DeleteFileUploadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteFileUpload(ctx context.Context, arg DeleteFileUploadParams) error {
	_, err := q.db.ExecContext(ctx, deleteFileUpload, arg.ID, arg.UserID)
	return err
}

const getFileUploadsByUserID = `-- name: GetFileUploadsByUserID :many
SELECT id, user_id, file_type, file_url, original_name, file_size, created_at FROM file_uploads WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetFileUploadsByUserID(ctx context.Context, userID uuid.UUID) ([]FileUpload, error) {
	rows, err := q.db.QueryContext(ctx, getFileUploadsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileUpload
	for rows.Next() {
		var i FileUpload
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileType,
			&i.FileUrl,
			&i.OriginalName,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
