// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gov_jobs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getGovJobByID = `-- name: GetGovJobByID :one
SELECT id, title, department, location, apply_url, last_date, 
       source, eligibility, vacancy_count, salary, exam_date, created_at
FROM jobs_government 
WHERE id = $1 AND is_active = true
`

type GetGovJobByIDRow struct {
	ID           uuid.UUID      `json:"id"`
	Title        string         `json:"title"`
	Department   sql.NullString `json:"department"`
	Location     sql.NullString `json:"location"`
	ApplyUrl     sql.NullString `json:"apply_url"`
	LastDate     sql.NullTime   `json:"last_date"`
	Source       string         `json:"source"`
	Eligibility  sql.NullString `json:"eligibility"`
	VacancyCount sql.NullInt32  `json:"vacancy_count"`
	Salary       sql.NullString `json:"salary"`
	ExamDate     sql.NullTime   `json:"exam_date"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetGovJobByID(ctx context.Context, id uuid.UUID) (GetGovJobByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGovJobByID, id)
	var i GetGovJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.Location,
		&i.ApplyUrl,
		&i.LastDate,
		&i.Source,
		&i.Eligibility,
		&i.VacancyCount,
		&i.Salary,
		&i.ExamDate,
		&i.CreatedAt,
	)
	return i, err
}

const getGovJobs = `-- name: GetGovJobs :many
SELECT id, title, department, location, apply_url, last_date, 
       source, eligibility, vacancy_count, salary, exam_date, created_at
FROM jobs_government 
WHERE is_active = true
  AND ($1::text = '' OR department ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR location ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR source = $3)
ORDER BY created_at DESC 
LIMIT $4 OFFSET $5
`

type GetGovJobsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetGovJobsRow struct {
	ID           uuid.UUID      `json:"id"`
	Title        string         `json:"title"`
	Department   sql.NullString `json:"department"`
	Location     sql.NullString `json:"location"`
	ApplyUrl     sql.NullString `json:"apply_url"`
	LastDate     sql.NullTime   `json:"last_date"`
	Source       string         `json:"source"`
	Eligibility  sql.NullString `json:"eligibility"`
	VacancyCount sql.NullInt32  `json:"vacancy_count"`
	Salary       sql.NullString `json:"salary"`
	ExamDate     sql.NullTime   `json:"exam_date"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetGovJobs(ctx context.Context, arg GetGovJobsParams) ([]GetGovJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGovJobs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGovJobsRow
	for rows.Next() {
		var i GetGovJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Department,
			&i.Location,
			&i.ApplyUrl,
			&i.LastDate,
			&i.Source,
			&i.Eligibility,
			&i.VacancyCount,
			&i.Salary,
			&i.ExamDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGovJobsCount = `-- name: GetGovJobsCount :one
SELECT COUNT(*) FROM jobs_government WHERE is_active = true
  AND ($1::text = '' OR department ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR location ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR source = $3)
`

type GetGovJobsCountParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) GetGovJobsCount(ctx context.Context, arg GetGovJobsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGovJobsCount, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}
