// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interviews.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInterview = `-- name: CreateInterview :one
INSERT INTO interviews (application_id, candidate_id, company_id, scheduled_at, room_url, meeting_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, application_id, candidate_id, company_id, scheduled_at, room_url, status, meeting_id, created_at, updated_at
`

type CreateInterviewParams struct {
	ApplicationID uuid.UUID      `json:"application_id"`
	CandidateID   uuid.UUID      `json:"candidate_id"`
	CompanyID     uuid.UUID      `json:"company_id"`
	ScheduledAt   time.Time      `json:"scheduled_at"`
	RoomUrl       sql.NullString `json:"room_url"`
	MeetingID     sql.NullString `json:"meeting_id"`
}

func (q *Queries) CreateInterview(ctx context.Context, arg CreateInterviewParams) (Interview, error) {
	row := q.db.QueryRowContext(ctx, createInterview,
		arg.ApplicationID,
		arg.CandidateID,
		arg.CompanyID,
		arg.ScheduledAt,
		arg.RoomUrl,
		arg.MeetingID,
	)
	var i Interview
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.CandidateID,
		&i.CompanyID,
		&i.ScheduledAt,
		&i.RoomUrl,
		&i.Status,
		&i.MeetingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInterviewByID = `-- name: GetInterviewByID :one
SELECT id, application_id, candidate_id, company_id, scheduled_at, room_url, status, meeting_id, created_at, updated_at FROM interviews WHERE id = $1
`

func (q *Queries) GetInterviewByID(ctx context.Context, id uuid.UUID) (Interview, error) {
	row := q.db.QueryRowContext(ctx, getInterviewByID, id)
	var i Interview
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.CandidateID,
		&i.CompanyID,
		&i.ScheduledAt,
		&i.RoomUrl,
		&i.Status,
		&i.MeetingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInterviewsByCandidate = `-- name: GetInterviewsByCandidate :many
SELECT id, application_id, candidate_id, company_id, scheduled_at, room_url, status, meeting_id, created_at, updated_at FROM interviews WHERE candidate_id = $1 ORDER BY scheduled_at DESC
`

func (q *Queries) GetInterviewsByCandidate(ctx context.Context, candidateID uuid.UUID) ([]Interview, error) {
	rows, err := q.db.QueryContext(ctx, getInterviewsByCandidate, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interview
	for rows.Next() {
		var i Interview
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.CandidateID,
			&i.CompanyID,
			&i.ScheduledAt,
			&i.RoomUrl,
			&i.Status,
			&i.MeetingID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInterviewsByCompany = `-- name: GetInterviewsByCompany :many
SELECT id, application_id, candidate_id, company_id, scheduled_at, room_url, status, meeting_id, created_at, updated_at FROM interviews WHERE company_id = $1 ORDER BY scheduled_at DESC
`

func (q *Queries) GetInterviewsByCompany(ctx context.Context, companyID uuid.UUID) ([]Interview, error) {
	rows, err := q.db.QueryContext(ctx, getInterviewsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interview
	for rows.Next() {
		var i Interview
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.CandidateID,
			&i.CompanyID,
			&i.ScheduledAt,
			&i.RoomUrl,
			&i.Status,
			&i.MeetingID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewStatus = `-- name: UpdateInterviewStatus :one
UPDATE interviews SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, application_id, candidate_id, company_id, scheduled_at, room_url, status, meeting_id, created_at, updated_at
`

type UpdateInterviewStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateInterviewStatus(ctx context.Context, arg UpdateInterviewStatusParams) (Interview, error) {
	row := q.db.QueryRowContext(ctx, updateInterviewStatus, arg.ID, arg.Status)
	var i Interview
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.CandidateID,
		&i.CompanyID,
		&i.ScheduledAt,
		&i.RoomUrl,
		&i.Status,
		&i.MeetingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
