// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_trades.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createJobTrade = `-- name: CreateJobTrade :one
INSERT INTO job_trades (category_id, name, slug, description, qualification_req, min_salary, max_salary, demand_level, icon)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, category_id, name, slug, description, qualification_req, min_salary, max_salary, demand_level, icon, is_active, created_at, updated_at
`

type CreateJobTradeParams struct {
	CategoryID       uuid.UUID      `json:"category_id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      sql.NullString `json:"description"`
	QualificationReq sql.NullString `json:"qualification_req"`
	MinSalary        sql.NullInt32  `json:"min_salary"`
	MaxSalary        sql.NullInt32  `json:"max_salary"`
	DemandLevel      string         `json:"demand_level"`
	Icon             sql.NullString `json:"icon"`
}

func (q *Queries) CreateJobTrade(ctx context.Context, arg CreateJobTradeParams) (JobTrade, error) {
	row := q.db.QueryRowContext(ctx, createJobTrade,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.QualificationReq,
		arg.MinSalary,
		arg.MaxSalary,
		arg.DemandLevel,
		arg.Icon,
	)
	var i JobTrade
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.QualificationReq,
		&i.MinSalary,
		&i.MaxSalary,
		&i.DemandLevel,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobTrade = `-- name: DeleteJobTrade :exec
DELETE FROM job_trades WHERE id = $1
`

func (q *Queries) DeleteJobTrade(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteJobTrade, id)
	return err
}

const getJobTradeByID = `-- name: GetJobTradeByID :one
SELECT id, category_id, name, slug, description, qualification_req, min_salary, max_salary, demand_level, icon, is_active, created_at, updated_at
FROM job_trades
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetJobTradeByID(ctx context.Context, id uuid.UUID) (JobTrade, error) {
	row := q.db.QueryRowContext(ctx, getJobTradeByID, id)
	var i JobTrade
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.QualificationReq,
		&i.MinSalary,
		&i.MaxSalary,
		&i.DemandLevel,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobTradeBySlug = `-- name: GetJobTradeBySlug :one
SELECT id, category_id, name, slug, description, qualification_req, min_salary, max_salary, demand_level, icon, is_active, created_at, updated_at
FROM job_trades
WHERE slug = $1 AND category_id = $2 AND is_active = true
`

type GetJobTradeBySlugParams struct {
	Slug       string    `json:"slug"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) GetJobTradeBySlug(ctx context.Context, arg GetJobTradeBySlugParams) (JobTrade, error) {
	row := q.db.QueryRowContext(ctx, getJobTradeBySlug, arg.Slug, arg.CategoryID)
	var i JobTrade
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.QualificationReq,
		&i.MinSalary,
		&i.MaxSalary,
		&i.DemandLevel,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobTrades = `-- name: GetJobTrades :many
SELECT id, category_id, name, slug, description, qualification_req, min_salary, max_salary, demand_level, icon, is_active, created_at, updated_at
FROM job_trades
WHERE is_active = true
  AND ($1::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR category_id = $1)
  AND ($2::text = '' OR demand_level = $2)
ORDER BY category_id, name ASC
`

type GetJobTradesParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) GetJobTrades(ctx context.Context, arg GetJobTradesParams) ([]JobTrade, error) {
	rows, err := q.db.QueryContext(ctx, getJobTrades, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobTrade
	for rows.Next() {
		var i JobTrade
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.QualificationReq,
			&i.MinSalary,
			&i.MaxSalary,
			&i.DemandLevel,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobTradesByCategory = `-- name: GetJobTradesByCategory :many
SELECT id, category_id, name, slug, description, qualification_req, min_salary, max_salary, demand_level, icon, is_active, created_at, updated_at
FROM job_trades
WHERE category_id = $1 AND is_active = true
ORDER BY name ASC
`

func (q *Queries) GetJobTradesByCategory(ctx context.Context, categoryID uuid.UUID) ([]JobTrade, error) {
	rows, err := q.db.QueryContext(ctx, getJobTradesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobTrade
	for rows.Next() {
		var i JobTrade
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.QualificationReq,
			&i.MinSalary,
			&i.MaxSalary,
			&i.DemandLevel,
			&i.Icon,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobTradesCount = `-- name: GetJobTradesCount :one
SELECT COUNT(*) FROM job_trades
WHERE is_active = true
  AND ($1::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR category_id = $1)
  AND ($2::text = '' OR demand_level = $2)
`

type GetJobTradesCountParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) GetJobTradesCount(ctx context.Context, arg GetJobTradesCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getJobTradesCount, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateJobTrade = `-- name: UpdateJobTrade :one
UPDATE job_trades
SET category_id = $2, name = $3, slug = $4, description = $5, qualification_req = $6, min_salary = $7, max_salary = $8, demand_level = $9, icon = $10, is_active = $11, updated_at = NOW()
WHERE id = $1
RETURNING id, category_id, name, slug, description, qualification_req, min_salary, max_salary, demand_level, icon, is_active, created_at, updated_at
`

type UpdateJobTradeParams struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      sql.NullString `json:"description"`
	QualificationReq sql.NullString `json:"qualification_req"`
	MinSalary        sql.NullInt32  `json:"min_salary"`
	MaxSalary        sql.NullInt32  `json:"max_salary"`
	DemandLevel      string         `json:"demand_level"`
	Icon             sql.NullString `json:"icon"`
	IsActive         bool           `json:"is_active"`
}

func (q *Queries) UpdateJobTrade(ctx context.Context, arg UpdateJobTradeParams) (JobTrade, error) {
	row := q.db.QueryRowContext(ctx, updateJobTrade,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.QualificationReq,
		arg.MinSalary,
		arg.MaxSalary,
		arg.DemandLevel,
		arg.Icon,
		arg.IsActive,
	)
	var i JobTrade
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.QualificationReq,
		&i.MinSalary,
		&i.MaxSalary,
		&i.DemandLevel,
		&i.Icon,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
