// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_categories.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createJobCategory = `-- name: CreateJobCategory :one
INSERT INTO job_categories (name, slug, description, icon, color, display_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, description, icon, color, display_order, is_active, created_at, updated_at
`

type CreateJobCategoryParams struct {
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	Icon         sql.NullString `json:"icon"`
	Color        sql.NullString `json:"color"`
	DisplayOrder int32          `json:"display_order"`
}

func (q *Queries) CreateJobCategory(ctx context.Context, arg CreateJobCategoryParams) (JobCategory, error) {
	row := q.db.QueryRowContext(ctx, createJobCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.DisplayOrder,
	)
	var i JobCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobCategory = `-- name: DeleteJobCategory :exec
DELETE FROM job_categories WHERE id = $1
`

func (q *Queries) DeleteJobCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteJobCategory, id)
	return err
}

const getJobCategories = `-- name: GetJobCategories :many
SELECT id, name, slug, description, icon, color, display_order, is_active, created_at, updated_at
FROM job_categories
WHERE is_active = true
ORDER BY display_order ASC
`

func (q *Queries) GetJobCategories(ctx context.Context) ([]JobCategory, error) {
	rows, err := q.db.QueryContext(ctx, getJobCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobCategory
	for rows.Next() {
		var i JobCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobCategoryByID = `-- name: GetJobCategoryByID :one
SELECT id, name, slug, description, icon, color, display_order, is_active, created_at, updated_at
FROM job_categories
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetJobCategoryByID(ctx context.Context, id uuid.UUID) (JobCategory, error) {
	row := q.db.QueryRowContext(ctx, getJobCategoryByID, id)
	var i JobCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobCategoryBySlug = `-- name: GetJobCategoryBySlug :one
SELECT id, name, slug, description, icon, color, display_order, is_active, created_at, updated_at
FROM job_categories
WHERE slug = $1 AND is_active = true
`

func (q *Queries) GetJobCategoryBySlug(ctx context.Context, slug string) (JobCategory, error) {
	row := q.db.QueryRowContext(ctx, getJobCategoryBySlug, slug)
	var i JobCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobCategory = `-- name: UpdateJobCategory :one
UPDATE job_categories
SET name = $2, slug = $3, description = $4, icon = $5, color = $6, display_order = $7, is_active = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, icon, color, display_order, is_active, created_at, updated_at
`

type UpdateJobCategoryParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	Icon         sql.NullString `json:"icon"`
	Color        sql.NullString `json:"color"`
	DisplayOrder int32          `json:"display_order"`
	IsActive     bool           `json:"is_active"`
}

func (q *Queries) UpdateJobCategory(ctx context.Context, arg UpdateJobCategoryParams) (JobCategory, error) {
	row := q.db.QueryRowContext(ctx, updateJobCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.DisplayOrder,
		arg.IsActive,
	)
	var i JobCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
