// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Candidate struct {
	ID                uuid.UUID             `json:"id"`
	UserID            uuid.UUID             `json:"user_id"`
	Phone             sql.NullString        `json:"phone"`
	ResumeUrl         sql.NullString        `json:"resume_url"`
	ResumeParsed      pqtype.NullRawMessage `json:"resume_parsed"`
	Skills            []string              `json:"skills"`
	ExperienceYears   sql.NullInt32         `json:"experience_years"`
	CurrentCompany    sql.NullString        `json:"current_company"`
	CurrentPosition   sql.NullString        `json:"current_position"`
	Location          sql.NullString        `json:"location"`
	LinkedinUrl       sql.NullString        `json:"linkedin_url"`
	GithubUrl         sql.NullString        `json:"github_url"`
	PortfolioUrl      sql.NullString        `json:"portfolio_url"`
	Bio               sql.NullString        `json:"bio"`
	IsOpenToWork      sql.NullBool          `json:"is_open_to_work"`
	ExpectedSalary    sql.NullString        `json:"expected_salary"`
	PreferredJobType  []string              `json:"preferred_job_type"`
	PreferredLocation []string              `json:"preferred_location"`
	CreatedAt         sql.NullTime          `json:"created_at"`
	UpdatedAt         sql.NullTime          `json:"updated_at"`
}

type Company struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Name         string         `json:"name"`
	Industry     sql.NullString `json:"industry"`
	CompanySize  sql.NullString `json:"company_size"`
	Website      sql.NullString `json:"website"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Description  sql.NullString `json:"description"`
	Headquarters sql.NullString `json:"headquarters"`
	FoundedYear  sql.NullInt32  `json:"founded_year"`
	IsVerified   sql.NullBool   `json:"is_verified"`
	IsActive     sql.NullBool   `json:"is_active"`
	ApprovedBy   uuid.NullUUID  `json:"approved_by"`
	ApprovedAt   sql.NullTime   `json:"approved_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type CompanyJob struct {
	ID                uuid.UUID      `json:"id"`
	CompanyID         uuid.UUID      `json:"company_id"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	Requirements      sql.NullString `json:"requirements"`
	Responsibilities  sql.NullString `json:"responsibilities"`
	Location          sql.NullString `json:"location"`
	JobType           sql.NullString `json:"job_type"`
	ExperienceMin     sql.NullInt32  `json:"experience_min"`
	ExperienceMax     sql.NullInt32  `json:"experience_max"`
	SalaryMin         sql.NullInt32  `json:"salary_min"`
	SalaryMax         sql.NullInt32  `json:"salary_max"`
	SalaryCurrency    sql.NullString `json:"salary_currency"`
	Skills            []string       `json:"skills"`
	Benefits          []string       `json:"benefits"`
	ApplicationUrl    sql.NullString `json:"application_url"`
	ApplicationEmail  sql.NullString `json:"application_email"`
	IsRemote          sql.NullBool   `json:"is_remote"`
	IsActive          sql.NullBool   `json:"is_active"`
	ViewsCount        sql.NullInt32  `json:"views_count"`
	ApplicationsCount sql.NullInt32  `json:"applications_count"`
	PostedAt          sql.NullTime   `json:"posted_at"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type Course struct {
	ID              uuid.UUID      `json:"id"`
	Provider        string         `json:"provider"`
	Title           string         `json:"title"`
	Url             string         `json:"url"`
	Duration        sql.NullString `json:"duration"`
	Mode            sql.NullString `json:"mode"`
	Level           sql.NullString `json:"level"`
	Skills          []string       `json:"skills"`
	Description     sql.NullString `json:"description"`
	ThumbnailUrl    sql.NullString `json:"thumbnail_url"`
	Price           sql.NullString `json:"price"`
	IsFree          sql.NullBool   `json:"is_free"`
	Source          string         `json:"source"`
	StartDate       sql.NullTime   `json:"start_date"`
	EndDate         sql.NullTime   `json:"end_date"`
	EnrollmentCount sql.NullInt32  `json:"enrollment_count"`
	Rating          sql.NullString `json:"rating"`
	IsActive        sql.NullBool   `json:"is_active"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type CrawledJob struct {
	ID                      int64                 `json:"id"`
	SourceID                sql.NullInt32         `json:"source_id"`
	ExternalJobID           string                `json:"external_job_id"`
	JobHash                 string                `json:"job_hash"`
	Title                   string                `json:"title"`
	Organization            string                `json:"organization"`
	JobType                 sql.NullString        `json:"job_type"`
	CategoryID              uuid.NullUUID         `json:"category_id"`
	TradeID                 uuid.NullUUID         `json:"trade_id"`
	QualificationRequired   sql.NullString        `json:"qualification_required"`
	TotalVacancies          sql.NullInt32         `json:"total_vacancies"`
	SalaryRange             sql.NullString        `json:"salary_range"`
	JobLocation             sql.NullString        `json:"job_location"`
	OfficialNotificationUrl sql.NullString        `json:"official_notification_url"`
	ApplyUrl                string                `json:"apply_url"`
	PublishedAt             sql.NullTime          `json:"published_at"`
	ApplicationDeadline     sql.NullTime          `json:"application_deadline"`
	Status                  sql.NullString        `json:"status"`
	RawPayload              pqtype.NullRawMessage `json:"raw_payload"`
	CreatedAt               sql.NullTime          `json:"created_at"`
	UpdatedAt               sql.NullTime          `json:"updated_at"`
}

type CrawlerLog struct {
	ID              int64          `json:"id"`
	Source          string         `json:"source"`
	Status          string         `json:"status"`
	JobsFound       sql.NullInt32  `json:"jobs_found"`
	JobsSaved       sql.NullInt32  `json:"jobs_saved"`
	DuplicatesFound sql.NullInt32  `json:"duplicates_found"`
	ErrorsCount     sql.NullInt32  `json:"errors_count"`
	Errors          sql.NullString `json:"errors"`
	ExecutionTimeMs sql.NullInt32  `json:"execution_time_ms"`
	StartedAt       sql.NullTime   `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type CrawlerSource struct {
	ID            int32        `json:"id"`
	Name          string       `json:"name"`
	SourceType    string       `json:"source_type"`
	BaseUrl       string       `json:"base_url"`
	IsActive      sql.NullBool `json:"is_active"`
	LastCrawledAt sql.NullTime `json:"last_crawled_at"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type EmailQueue struct {
	ID            uuid.UUID      `json:"id"`
	ToEmail       string         `json:"to_email"`
	Subject       string         `json:"subject"`
	Body          string         `json:"body"`
	Status        string         `json:"status"`
	Attempts      int32          `json:"attempts"`
	LastAttemptAt sql.NullTime   `json:"last_attempt_at"`
	SentAt        sql.NullTime   `json:"sent_at"`
	ErrorMessage  sql.NullString `json:"error_message"`
	CreatedAt     time.Time      `json:"created_at"`
}

type FileUpload struct {
	ID           uuid.UUID     `json:"id"`
	UserID       uuid.UUID     `json:"user_id"`
	FileType     string        `json:"file_type"`
	FileUrl      string        `json:"file_url"`
	OriginalName string        `json:"original_name"`
	FileSize     sql.NullInt64 `json:"file_size"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}

type Interview struct {
	ID            uuid.UUID      `json:"id"`
	ApplicationID uuid.UUID      `json:"application_id"`
	CandidateID   uuid.UUID      `json:"candidate_id"`
	CompanyID     uuid.UUID      `json:"company_id"`
	ScheduledAt   time.Time      `json:"scheduled_at"`
	RoomUrl       sql.NullString `json:"room_url"`
	Status        string         `json:"status"`
	MeetingID     sql.NullString `json:"meeting_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type JobApplication struct {
	ID          uuid.UUID       `json:"id"`
	JobID       uuid.UUID       `json:"job_id"`
	CandidateID uuid.UUID       `json:"candidate_id"`
	Status      sql.NullString  `json:"status"`
	CoverLetter sql.NullString  `json:"cover_letter"`
	ResumeUrl   sql.NullString  `json:"resume_url"`
	MatchScore  sql.NullFloat64 `json:"match_score"`
	Notes       sql.NullString  `json:"notes"`
	AppliedAt   sql.NullTime    `json:"applied_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}

type JobCategory struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	Icon         sql.NullString `json:"icon"`
	Color        sql.NullString `json:"color"`
	DisplayOrder int32          `json:"display_order"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type JobTrade struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      sql.NullString `json:"description"`
	QualificationReq sql.NullString `json:"qualification_req"`
	MinSalary        sql.NullInt32  `json:"min_salary"`
	MaxSalary        sql.NullInt32  `json:"max_salary"`
	DemandLevel      string         `json:"demand_level"`
	Icon             sql.NullString `json:"icon"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type JobsGovernment struct {
	ID                 uuid.UUID      `json:"id"`
	Title              string         `json:"title"`
	Department         sql.NullString `json:"department"`
	Location           sql.NullString `json:"location"`
	ApplyUrl           sql.NullString `json:"apply_url"`
	LastDate           sql.NullTime   `json:"last_date"`
	Source             string         `json:"source"`
	Eligibility        sql.NullString `json:"eligibility"`
	VacancyCount       sql.NullInt32  `json:"vacancy_count"`
	Salary             sql.NullString `json:"salary"`
	ExamDate           sql.NullTime   `json:"exam_date"`
	NotificationPdfUrl sql.NullString `json:"notification_pdf_url"`
	IsActive           sql.NullBool   `json:"is_active"`
	JobHash            sql.NullString `json:"job_hash"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type JobsPrivate struct {
	ID          uuid.UUID      `json:"id"`
	Company     string         `json:"company"`
	Title       string         `json:"title"`
	Location    sql.NullString `json:"location"`
	Url         sql.NullString `json:"url"`
	Salary      sql.NullString `json:"salary"`
	Experience  sql.NullString `json:"experience"`
	JobType     sql.NullString `json:"job_type"`
	Skills      []string       `json:"skills"`
	Description sql.NullString `json:"description"`
	Source      string         `json:"source"`
	PostedAt    sql.NullTime   `json:"posted_at"`
	IsActive    sql.NullBool   `json:"is_active"`
	JobHash     sql.NullString `json:"job_hash"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type PlatformStat struct {
	ID                uuid.UUID `json:"id"`
	TotalJobs         int64     `json:"total_jobs"`
	TotalCandidates   int64     `json:"total_candidates"`
	TotalCompanies    int64     `json:"total_companies"`
	TotalPlacements   int64     `json:"total_placements"`
	TotalApplications int64     `json:"total_applications"`
	VisitsToday       int64     `json:"visits_today"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	IpHash    sql.NullString `json:"ip_hash"`
	UaHash    sql.NullString `json:"ua_hash"`
	ExpiresAt time.Time      `json:"expires_at"`
	Revoked   bool           `json:"revoked"`
	CreatedAt time.Time      `json:"created_at"`
}

type SavedJob struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	GovJobID  uuid.NullUUID `json:"gov_job_id"`
	PrivJobID uuid.NullUUID `json:"priv_job_id"`
	CreatedAt time.Time     `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
	Phone        sql.NullString `json:"phone"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	IsActive     sql.NullBool   `json:"is_active"`
	IsVerified   sql.NullBool   `json:"is_verified"`
	LastLogin    sql.NullTime   `json:"last_login"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type UserEnrollment struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.UUID       `json:"user_id"`
	TradeID     uuid.UUID       `json:"trade_id"`
	Status      string          `json:"status"`
	EnrolledAt  time.Time       `json:"enrolled_at"`
	ExpiresAt   time.Time       `json:"expires_at"`
	CompletedAt sql.NullTime    `json:"completed_at"`
	ProgressPct int32           `json:"progress_pct"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type UserNotificationLog struct {
	ID               uuid.UUID       `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	EnrollmentID     uuid.NullUUID   `json:"enrollment_id"`
	NotificationType string          `json:"notification_type"`
	Channel          string          `json:"channel"`
	Title            string          `json:"title"`
	Message          string          `json:"message"`
	Payload          json.RawMessage `json:"payload"`
	SentAt           time.Time       `json:"sent_at"`
	ReadAt           sql.NullTime    `json:"read_at"`
	ClickedAt        sql.NullTime    `json:"clicked_at"`
	CreatedAt        time.Time       `json:"created_at"`
}

type YoutubeVideo struct {
	ID          uuid.UUID      `json:"id"`
	Channel     string         `json:"channel"`
	ChannelID   sql.NullString `json:"channel_id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Thumbnail   sql.NullString `json:"thumbnail"`
	Description sql.NullString `json:"description"`
	VideoID     string         `json:"video_id"`
	PublishedAt sql.NullTime   `json:"published_at"`
	Duration    sql.NullString `json:"duration"`
	ViewCount   sql.NullInt64  `json:"view_count"`
	LikeCount   sql.NullInt64  `json:"like_count"`
	Category    sql.NullString `json:"category"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
