// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Candidate struct {
	ID                uuid.UUID             `json:"id"`
	UserID            uuid.UUID             `json:"user_id"`
	Phone             sql.NullString        `json:"phone"`
	ResumeUrl         sql.NullString        `json:"resume_url"`
	ResumeParsed      pqtype.NullRawMessage `json:"resume_parsed"`
	Skills            []string              `json:"skills"`
	ExperienceYears   sql.NullInt32         `json:"experience_years"`
	CurrentCompany    sql.NullString        `json:"current_company"`
	CurrentPosition   sql.NullString        `json:"current_position"`
	Location          sql.NullString        `json:"location"`
	LinkedinUrl       sql.NullString        `json:"linkedin_url"`
	GithubUrl         sql.NullString        `json:"github_url"`
	PortfolioUrl      sql.NullString        `json:"portfolio_url"`
	Bio               sql.NullString        `json:"bio"`
	IsOpenToWork      sql.NullBool          `json:"is_open_to_work"`
	ExpectedSalary    sql.NullString        `json:"expected_salary"`
	PreferredJobType  []string              `json:"preferred_job_type"`
	PreferredLocation []string              `json:"preferred_location"`
	CreatedAt         sql.NullTime          `json:"created_at"`
	UpdatedAt         sql.NullTime          `json:"updated_at"`
}

type Company struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Name         string         `json:"name"`
	Industry     sql.NullString `json:"industry"`
	CompanySize  sql.NullString `json:"company_size"`
	Website      sql.NullString `json:"website"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Description  sql.NullString `json:"description"`
	Headquarters sql.NullString `json:"headquarters"`
	FoundedYear  sql.NullInt32  `json:"founded_year"`
	IsVerified   sql.NullBool   `json:"is_verified"`
	IsActive     sql.NullBool   `json:"is_active"`
	ApprovedBy   uuid.NullUUID  `json:"approved_by"`
	ApprovedAt   sql.NullTime   `json:"approved_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type CompanyJob struct {
	ID                uuid.UUID      `json:"id"`
	CompanyID         uuid.UUID      `json:"company_id"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	Requirements      sql.NullString `json:"requirements"`
	Responsibilities  sql.NullString `json:"responsibilities"`
	Location          sql.NullString `json:"location"`
	JobType           sql.NullString `json:"job_type"`
	ExperienceMin     sql.NullInt32  `json:"experience_min"`
	ExperienceMax     sql.NullInt32  `json:"experience_max"`
	SalaryMin         sql.NullInt32  `json:"salary_min"`
	SalaryMax         sql.NullInt32  `json:"salary_max"`
	SalaryCurrency    sql.NullString `json:"salary_currency"`
	Skills            []string       `json:"skills"`
	Benefits          []string       `json:"benefits"`
	ApplicationUrl    sql.NullString `json:"application_url"`
	ApplicationEmail  sql.NullString `json:"application_email"`
	IsRemote          sql.NullBool   `json:"is_remote"`
	IsActive          sql.NullBool   `json:"is_active"`
	ViewsCount        sql.NullInt32  `json:"views_count"`
	ApplicationsCount sql.NullInt32  `json:"applications_count"`
	PostedAt          sql.NullTime   `json:"posted_at"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type Course struct {
	ID              uuid.UUID      `json:"id"`
	Provider        string         `json:"provider"`
	Title           string         `json:"title"`
	Url             string         `json:"url"`
	Duration        sql.NullString `json:"duration"`
	Mode            sql.NullString `json:"mode"`
	Level           sql.NullString `json:"level"`
	Skills          []string       `json:"skills"`
	Description     sql.NullString `json:"description"`
	ThumbnailUrl    sql.NullString `json:"thumbnail_url"`
	Price           sql.NullString `json:"price"`
	IsFree          sql.NullBool   `json:"is_free"`
	Source          string         `json:"source"`
	StartDate       sql.NullTime   `json:"start_date"`
	EndDate         sql.NullTime   `json:"end_date"`
	EnrollmentCount sql.NullInt32  `json:"enrollment_count"`
	Rating          sql.NullString `json:"rating"`
	IsActive        sql.NullBool   `json:"is_active"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type JobApplication struct {
	ID          uuid.UUID       `json:"id"`
	JobID       uuid.UUID       `json:"job_id"`
	CandidateID uuid.UUID       `json:"candidate_id"`
	Status      sql.NullString  `json:"status"`
	CoverLetter sql.NullString  `json:"cover_letter"`
	ResumeUrl   sql.NullString  `json:"resume_url"`
	MatchScore  sql.NullFloat64 `json:"match_score"`
	Notes       sql.NullString  `json:"notes"`
	AppliedAt   sql.NullTime    `json:"applied_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}

type JobsGovernment struct {
	ID                 uuid.UUID      `json:"id"`
	Title              string         `json:"title"`
	Department         sql.NullString `json:"department"`
	Location           sql.NullString `json:"location"`
	ApplyUrl           sql.NullString `json:"apply_url"`
	LastDate           sql.NullTime   `json:"last_date"`
	Source             string         `json:"source"`
	Eligibility        sql.NullString `json:"eligibility"`
	VacancyCount       sql.NullInt32  `json:"vacancy_count"`
	Salary             sql.NullString `json:"salary"`
	ExamDate           sql.NullTime   `json:"exam_date"`
	NotificationPdfUrl sql.NullString `json:"notification_pdf_url"`
	IsActive           sql.NullBool   `json:"is_active"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type JobsPrivate struct {
	ID          uuid.UUID      `json:"id"`
	Company     string         `json:"company"`
	Title       string         `json:"title"`
	Location    sql.NullString `json:"location"`
	Url         sql.NullString `json:"url"`
	Salary      sql.NullString `json:"salary"`
	Experience  sql.NullString `json:"experience"`
	JobType     sql.NullString `json:"job_type"`
	Skills      []string       `json:"skills"`
	Description sql.NullString `json:"description"`
	Source      string         `json:"source"`
	PostedAt    sql.NullTime   `json:"posted_at"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	IpHash    sql.NullString `json:"ip_hash"`
	UaHash    sql.NullString `json:"ua_hash"`
	ExpiresAt time.Time      `json:"expires_at"`
	Revoked   bool           `json:"revoked"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
	Phone        sql.NullString `json:"phone"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	IsActive     sql.NullBool   `json:"is_active"`
	IsVerified   sql.NullBool   `json:"is_verified"`
	LastLogin    sql.NullTime   `json:"last_login"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type YoutubeVideo struct {
	ID          uuid.UUID      `json:"id"`
	Channel     string         `json:"channel"`
	ChannelID   sql.NullString `json:"channel_id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Thumbnail   sql.NullString `json:"thumbnail"`
	Description sql.NullString `json:"description"`
	VideoID     string         `json:"video_id"`
	PublishedAt sql.NullTime   `json:"published_at"`
	Duration    sql.NullString `json:"duration"`
	ViewCount   sql.NullInt64  `json:"view_count"`
	LikeCount   sql.NullInt64  `json:"like_count"`
	Category    sql.NullString `json:"category"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
