// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_stats.sql

package db

import (
	"context"
)

const getPlatformStats = `-- name: GetPlatformStats :one
SELECT id, total_jobs, total_candidates, total_companies, total_placements, total_applications, visits_today, updated_at FROM platform_stats LIMIT 1
`

func (q *Queries) GetPlatformStats(ctx context.Context) (PlatformStat, error) {
	row := q.db.QueryRowContext(ctx, getPlatformStats)
	var i PlatformStat
	err := row.Scan(
		&i.ID,
		&i.TotalJobs,
		&i.TotalCandidates,
		&i.TotalCompanies,
		&i.TotalPlacements,
		&i.TotalApplications,
		&i.VisitsToday,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementVisits = `-- name: IncrementVisits :exec
UPDATE platform_stats SET visits_today = visits_today + 1 WHERE id = (SELECT id FROM platform_stats LIMIT 1)
`

func (q *Queries) IncrementVisits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, incrementVisits)
	return err
}

const updatePlatformStats = `-- name: UpdatePlatformStats :one
UPDATE platform_stats
SET total_jobs = $1, total_candidates = $2, total_companies = $3, total_placements = $4, total_applications = $5, visits_today = $6, updated_at = NOW()
WHERE id = (SELECT id FROM platform_stats LIMIT 1)
RETURNING id, total_jobs, total_candidates, total_companies, total_placements, total_applications, visits_today, updated_at
`

type UpdatePlatformStatsParams struct {
	TotalJobs         int64 `json:"total_jobs"`
	TotalCandidates   int64 `json:"total_candidates"`
	TotalCompanies    int64 `json:"total_companies"`
	TotalPlacements   int64 `json:"total_placements"`
	TotalApplications int64 `json:"total_applications"`
	VisitsToday       int64 `json:"visits_today"`
}

func (q *Queries) UpdatePlatformStats(ctx context.Context, arg UpdatePlatformStatsParams) (PlatformStat, error) {
	row := q.db.QueryRowContext(ctx, updatePlatformStats,
		arg.TotalJobs,
		arg.TotalCandidates,
		arg.TotalCompanies,
		arg.TotalPlacements,
		arg.TotalApplications,
		arg.VisitsToday,
	)
	var i PlatformStat
	err := row.Scan(
		&i.ID,
		&i.TotalJobs,
		&i.TotalCandidates,
		&i.TotalCompanies,
		&i.TotalPlacements,
		&i.TotalApplications,
		&i.VisitsToday,
		&i.UpdatedAt,
	)
	return i, err
}
