// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_jobs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteSavedJob = `-- name: DeleteSavedJob :exec
DELETE FROM saved_jobs WHERE id = $1 AND user_id = $2
`

type DeleteSavedJobParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSavedJob(ctx context.Context, arg DeleteSavedJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteSavedJob, arg.ID, arg.UserID)
	return err
}

const getSavedJobsByUser = `-- name: GetSavedJobsByUser :many
SELECT sj.id, sj.user_id, sj.gov_job_id, sj.priv_job_id, sj.created_at, g.title as gov_title, p.title as priv_title, p.company as priv_company
FROM saved_jobs sj
LEFT JOIN jobs_government g ON sj.gov_job_id = g.id
LEFT JOIN jobs_private p ON sj.priv_job_id = p.id
WHERE sj.user_id = $1
ORDER BY sj.created_at DESC
`

type GetSavedJobsByUserRow struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	GovJobID    uuid.NullUUID  `json:"gov_job_id"`
	PrivJobID   uuid.NullUUID  `json:"priv_job_id"`
	CreatedAt   time.Time      `json:"created_at"`
	GovTitle    sql.NullString `json:"gov_title"`
	PrivTitle   sql.NullString `json:"priv_title"`
	PrivCompany sql.NullString `json:"priv_company"`
}

func (q *Queries) GetSavedJobsByUser(ctx context.Context, userID uuid.UUID) ([]GetSavedJobsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getSavedJobsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSavedJobsByUserRow
	for rows.Next() {
		var i GetSavedJobsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GovJobID,
			&i.PrivJobID,
			&i.CreatedAt,
			&i.GovTitle,
			&i.PrivTitle,
			&i.PrivCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJob = `-- name: SaveJob :one
INSERT INTO saved_jobs (user_id, gov_job_id, priv_job_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, gov_job_id, priv_job_id, created_at
`

type SaveJobParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	GovJobID  uuid.NullUUID `json:"gov_job_id"`
	PrivJobID uuid.NullUUID `json:"priv_job_id"`
}

func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) (SavedJob, error) {
	row := q.db.QueryRowContext(ctx, saveJob, arg.UserID, arg.GovJobID, arg.PrivJobID)
	var i SavedJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GovJobID,
		&i.PrivJobID,
		&i.CreatedAt,
	)
	return i, err
}
