// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const searchCompanyJobs = `-- name: SearchCompanyJobs :many
SELECT 
    cj.id,
    cj.title,
    cj.description,
    cj.location,
    cj.job_type,
    cj.salary_min,
    cj.salary_max,
    cj.skills,
    cj.is_remote,
    cj.created_at,
    c.name as company_name,
    ts_rank(cj.search_vector, plainto_tsquery('english', $1)) as rank
FROM company_jobs cj
LEFT JOIN companies c ON cj.company_id = c.id
WHERE 
    cj.is_active = true
    AND (
        cj.search_vector @@ plainto_tsquery('english', $1)
        OR cj.title ILIKE '%' || $2 || '%'
        OR cj.description ILIKE '%' || $2 || '%'
        OR cj.location ILIKE '%' || $2 || '%'
        OR c.name ILIKE '%' || $2 || '%'
    )
ORDER BY rank DESC, cj.created_at DESC
LIMIT $3 OFFSET $4
`

type SearchCompanyJobsParams struct {
	PlaintoTsquery string         `json:"plainto_tsquery"`
	Column2        sql.NullString `json:"column_2"`
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
}

type SearchCompanyJobsRow struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Location    sql.NullString `json:"location"`
	JobType     sql.NullString `json:"job_type"`
	SalaryMin   sql.NullInt32  `json:"salary_min"`
	SalaryMax   sql.NullInt32  `json:"salary_max"`
	Skills      []string       `json:"skills"`
	IsRemote    sql.NullBool   `json:"is_remote"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	CompanyName sql.NullString `json:"company_name"`
	Rank        float32        `json:"rank"`
}

func (q *Queries) SearchCompanyJobs(ctx context.Context, arg SearchCompanyJobsParams) ([]SearchCompanyJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCompanyJobs,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCompanyJobsRow
	for rows.Next() {
		var i SearchCompanyJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.JobType,
			&i.SalaryMin,
			&i.SalaryMax,
			pq.Array(&i.Skills),
			&i.IsRemote,
			&i.CreatedAt,
			&i.CompanyName,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCompanyJobsCount = `-- name: SearchCompanyJobsCount :one
SELECT COUNT(*)
FROM company_jobs cj
LEFT JOIN companies c ON cj.company_id = c.id
WHERE 
    cj.is_active = true
    AND (
        cj.search_vector @@ plainto_tsquery('english', $1)
        OR cj.title ILIKE '%' || $2 || '%'
        OR cj.description ILIKE '%' || $2 || '%'
        OR cj.location ILIKE '%' || $2 || '%'
        OR c.name ILIKE '%' || $2 || '%'
    )
`

type SearchCompanyJobsCountParams struct {
	PlaintoTsquery string         `json:"plainto_tsquery"`
	Column2        sql.NullString `json:"column_2"`
}

func (q *Queries) SearchCompanyJobsCount(ctx context.Context, arg SearchCompanyJobsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, searchCompanyJobsCount, arg.PlaintoTsquery, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchGovJobs = `-- name: SearchGovJobs :many
SELECT 
    id,
    title,
    department,
    location,
    apply_url,
    last_date,
    source,
    eligibility,
    vacancy_count,
    salary,
    exam_date,
    created_at,
    ts_rank(search_vector, plainto_tsquery('english', $1)) as rank
FROM jobs_government
WHERE 
    is_active = true
    AND (
        search_vector @@ plainto_tsquery('english', $1)
        OR title ILIKE '%' || $2 || '%'
        OR department ILIKE '%' || $2 || '%'
        OR location ILIKE '%' || $2 || '%'
        OR eligibility ILIKE '%' || $2 || '%'
    )
ORDER BY rank DESC, created_at DESC
LIMIT $3 OFFSET $4
`

type SearchGovJobsParams struct {
	PlaintoTsquery string         `json:"plainto_tsquery"`
	Column2        sql.NullString `json:"column_2"`
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
}

type SearchGovJobsRow struct {
	ID           uuid.UUID      `json:"id"`
	Title        string         `json:"title"`
	Department   sql.NullString `json:"department"`
	Location     sql.NullString `json:"location"`
	ApplyUrl     sql.NullString `json:"apply_url"`
	LastDate     sql.NullTime   `json:"last_date"`
	Source       string         `json:"source"`
	Eligibility  sql.NullString `json:"eligibility"`
	VacancyCount sql.NullInt32  `json:"vacancy_count"`
	Salary       sql.NullString `json:"salary"`
	ExamDate     sql.NullTime   `json:"exam_date"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	Rank         float32        `json:"rank"`
}

func (q *Queries) SearchGovJobs(ctx context.Context, arg SearchGovJobsParams) ([]SearchGovJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchGovJobs,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchGovJobsRow
	for rows.Next() {
		var i SearchGovJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Department,
			&i.Location,
			&i.ApplyUrl,
			&i.LastDate,
			&i.Source,
			&i.Eligibility,
			&i.VacancyCount,
			&i.Salary,
			&i.ExamDate,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGovJobsCount = `-- name: SearchGovJobsCount :one
SELECT COUNT(*)
FROM jobs_government
WHERE 
    is_active = true
    AND (
        search_vector @@ plainto_tsquery('english', $1)
        OR title ILIKE '%' || $2 || '%'
        OR department ILIKE '%' || $2 || '%'
        OR location ILIKE '%' || $2 || '%'
        OR eligibility ILIKE '%' || $2 || '%'
    )
`

type SearchGovJobsCountParams struct {
	PlaintoTsquery string         `json:"plainto_tsquery"`
	Column2        sql.NullString `json:"column_2"`
}

func (q *Queries) SearchGovJobsCount(ctx context.Context, arg SearchGovJobsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, searchGovJobsCount, arg.PlaintoTsquery, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchPrivJobs = `-- name: SearchPrivJobs :many
SELECT 
    id,
    company,
    title,
    location,
    url,
    salary,
    experience,
    job_type,
    skills,
    description,
    source,
    posted_at,
    created_at,
    ts_rank(search_vector, plainto_tsquery('english', $1)) as rank
FROM jobs_private
WHERE 
    is_active = true
    AND (
        search_vector @@ plainto_tsquery('english', $1)
        OR title ILIKE '%' || $2 || '%'
        OR company ILIKE '%' || $2 || '%'
        OR location ILIKE '%' || $2 || '%'
        OR description ILIKE '%' || $2 || '%'
    )
ORDER BY rank DESC, created_at DESC
LIMIT $3 OFFSET $4
`

type SearchPrivJobsParams struct {
	PlaintoTsquery string         `json:"plainto_tsquery"`
	Column2        sql.NullString `json:"column_2"`
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
}

type SearchPrivJobsRow struct {
	ID          uuid.UUID      `json:"id"`
	Company     string         `json:"company"`
	Title       string         `json:"title"`
	Location    sql.NullString `json:"location"`
	Url         sql.NullString `json:"url"`
	Salary      sql.NullString `json:"salary"`
	Experience  sql.NullString `json:"experience"`
	JobType     sql.NullString `json:"job_type"`
	Skills      []string       `json:"skills"`
	Description sql.NullString `json:"description"`
	Source      string         `json:"source"`
	PostedAt    sql.NullTime   `json:"posted_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	Rank        float32        `json:"rank"`
}

func (q *Queries) SearchPrivJobs(ctx context.Context, arg SearchPrivJobsParams) ([]SearchPrivJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPrivJobs,
		arg.PlaintoTsquery,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPrivJobsRow
	for rows.Next() {
		var i SearchPrivJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.Salary,
			&i.Experience,
			&i.JobType,
			pq.Array(&i.Skills),
			&i.Description,
			&i.Source,
			&i.PostedAt,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPrivJobsCount = `-- name: SearchPrivJobsCount :one
SELECT COUNT(*)
FROM jobs_private
WHERE 
    is_active = true
    AND (
        search_vector @@ plainto_tsquery('english', $1)
        OR title ILIKE '%' || $2 || '%'
        OR company ILIKE '%' || $2 || '%'
        OR location ILIKE '%' || $2 || '%'
        OR description ILIKE '%' || $2 || '%'
    )
`

type SearchPrivJobsCountParams struct {
	PlaintoTsquery string         `json:"plainto_tsquery"`
	Column2        sql.NullString `json:"column_2"`
}

func (q *Queries) SearchPrivJobsCount(ctx context.Context, arg SearchPrivJobsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, searchPrivJobsCount, arg.PlaintoTsquery, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unifiedSearch = `-- name: UnifiedSearch :many

SELECT 
    'gov' as job_type,
    id,
    title,
    department,
    location,
    apply_url,
    last_date,
    source,
    eligibility,
    vacancy_count,
    salary,
    exam_date,
    created_at,
    ts_rank(search_vector, plainto_tsquery('english', $1)) as rank
FROM jobs_government
WHERE 
    is_active = true
    AND search_vector @@ plainto_tsquery('english', $1)

UNION ALL

SELECT 
    'private' as job_type,
    id,
    company as department,
    location,
    url as apply_url,
    posted_at as last_date,
    source,
    description as eligibility,
    0 as vacancy_count,
    salary,
    NULL as exam_date,
    created_at,
    ts_rank(search_vector, plainto_tsquery('english', $1)) as rank
FROM jobs_private
WHERE 
    is_active = true
    AND search_vector @@ plainto_tsquery('english', $1)

ORDER BY rank DESC
LIMIT $2 OFFSET $3
`

type UnifiedSearchParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

type UnifiedSearchRow struct {
	JobType      string         `json:"job_type"`
	ID           uuid.UUID      `json:"id"`
	Title        string         `json:"title"`
	Department   sql.NullString `json:"department"`
	Location     sql.NullString `json:"location"`
	ApplyUrl     sql.NullString `json:"apply_url"`
	LastDate     sql.NullTime   `json:"last_date"`
	Source       string         `json:"source"`
	Eligibility  sql.NullString `json:"eligibility"`
	VacancyCount sql.NullInt32  `json:"vacancy_count"`
	Salary       sql.NullString `json:"salary"`
	ExamDate     sql.NullTime   `json:"exam_date"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	Rank         float32        `json:"rank"`
}

// Search queries using full-text search and pg_trgm
// Unified search across government and private jobs using plainto_tsquery
func (q *Queries) UnifiedSearch(ctx context.Context, arg UnifiedSearchParams) ([]UnifiedSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, unifiedSearch, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnifiedSearchRow
	for rows.Next() {
		var i UnifiedSearchRow
		if err := rows.Scan(
			&i.JobType,
			&i.ID,
			&i.Title,
			&i.Department,
			&i.Location,
			&i.ApplyUrl,
			&i.LastDate,
			&i.Source,
			&i.Eligibility,
			&i.VacancyCount,
			&i.Salary,
			&i.ExamDate,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unifiedSearchCount = `-- name: UnifiedSearchCount :one
SELECT COUNT(*) FROM (
    SELECT 1 FROM jobs_government
    WHERE is_active = true AND search_vector @@ plainto_tsquery('english', $1)
    UNION ALL
    SELECT 1 FROM jobs_private
    WHERE is_active = true AND search_vector @@ plainto_tsquery('english', $1)
) as combined
`

func (q *Queries) UnifiedSearchCount(ctx context.Context, plaintoTsquery string) (int64, error) {
	row := q.db.QueryRowContext(ctx, unifiedSearchCount, plaintoTsquery)
	var count int64
	err := row.Scan(&count)
	return count, err
}
