// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_notification_logs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createNotificationLog = `-- name: CreateNotificationLog :one
INSERT INTO user_notification_logs (user_id, enrollment_id, notification_type, channel, title, message, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, enrollment_id, notification_type, channel, title, message, payload, sent_at, read_at, clicked_at, created_at
`

type CreateNotificationLogParams struct {
	UserID           uuid.UUID       `json:"user_id"`
	EnrollmentID     uuid.NullUUID   `json:"enrollment_id"`
	NotificationType string          `json:"notification_type"`
	Channel          string          `json:"channel"`
	Title            string          `json:"title"`
	Message          string          `json:"message"`
	Payload          json.RawMessage `json:"payload"`
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) (UserNotificationLog, error) {
	row := q.db.QueryRowContext(ctx, createNotificationLog,
		arg.UserID,
		arg.EnrollmentID,
		arg.NotificationType,
		arg.Channel,
		arg.Title,
		arg.Message,
		arg.Payload,
	)
	var i UserNotificationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EnrollmentID,
		&i.NotificationType,
		&i.Channel,
		&i.Title,
		&i.Message,
		&i.Payload,
		&i.SentAt,
		&i.ReadAt,
		&i.ClickedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotificationLog = `-- name: DeleteNotificationLog :exec
DELETE FROM user_notification_logs WHERE id = $1
`

func (q *Queries) DeleteNotificationLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationLog, id)
	return err
}

const getDailyNotificationCount = `-- name: GetDailyNotificationCount :one
SELECT COUNT(*) FROM user_notification_logs
WHERE user_id = $1
  AND DATE(sent_at) = CURRENT_DATE
`

func (q *Queries) GetDailyNotificationCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDailyNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDailyNotificationCountByType = `-- name: GetDailyNotificationCountByType :one
SELECT COUNT(*) FROM user_notification_logs
WHERE user_id = $1
  AND DATE(sent_at) = CURRENT_DATE
  AND notification_type = $2
`

type GetDailyNotificationCountByTypeParams struct {
	UserID           uuid.UUID `json:"user_id"`
	NotificationType string    `json:"notification_type"`
}

func (q *Queries) GetDailyNotificationCountByType(ctx context.Context, arg GetDailyNotificationCountByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDailyNotificationCountByType, arg.UserID, arg.NotificationType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotificationLogByID = `-- name: GetNotificationLogByID :one
SELECT id, user_id, enrollment_id, notification_type, channel, title, message, payload, sent_at, read_at, clicked_at, created_at
FROM user_notification_logs
WHERE id = $1
`

func (q *Queries) GetNotificationLogByID(ctx context.Context, id uuid.UUID) (UserNotificationLog, error) {
	row := q.db.QueryRowContext(ctx, getNotificationLogByID, id)
	var i UserNotificationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EnrollmentID,
		&i.NotificationType,
		&i.Channel,
		&i.Title,
		&i.Message,
		&i.Payload,
		&i.SentAt,
		&i.ReadAt,
		&i.ClickedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserNotificationLogs = `-- name: GetUserNotificationLogs :many
SELECT id, user_id, enrollment_id, notification_type, channel, title, message, payload, sent_at, read_at, clicked_at, created_at
FROM user_notification_logs
WHERE user_id = $1
  AND ($2::text = '' OR notification_type = $2)
ORDER BY sent_at DESC
LIMIT $3 OFFSET $4
`

type GetUserNotificationLogsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetUserNotificationLogs(ctx context.Context, arg GetUserNotificationLogsParams) ([]UserNotificationLog, error) {
	rows, err := q.db.QueryContext(ctx, getUserNotificationLogs,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserNotificationLog
	for rows.Next() {
		var i UserNotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EnrollmentID,
			&i.NotificationType,
			&i.Channel,
			&i.Title,
			&i.Message,
			&i.Payload,
			&i.SentAt,
			&i.ReadAt,
			&i.ClickedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNotificationLogsCount = `-- name: GetUserNotificationLogsCount :one
SELECT COUNT(*) FROM user_notification_logs
WHERE user_id = $1
  AND ($2::text = '' OR notification_type = $2)
`

type GetUserNotificationLogsCountParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) GetUserNotificationLogsCount(ctx context.Context, arg GetUserNotificationLogsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserNotificationLogsCount, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markNotificationClicked = `-- name: MarkNotificationClicked :one
UPDATE user_notification_logs
SET clicked_at = NOW()
WHERE id = $1
RETURNING id, user_id, enrollment_id, notification_type, channel, title, message, payload, sent_at, read_at, clicked_at, created_at
`

func (q *Queries) MarkNotificationClicked(ctx context.Context, id uuid.UUID) (UserNotificationLog, error) {
	row := q.db.QueryRowContext(ctx, markNotificationClicked, id)
	var i UserNotificationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EnrollmentID,
		&i.NotificationType,
		&i.Channel,
		&i.Title,
		&i.Message,
		&i.Payload,
		&i.SentAt,
		&i.ReadAt,
		&i.ClickedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE user_notification_logs
SET read_at = NOW()
WHERE id = $1
RETURNING id, user_id, enrollment_id, notification_type, channel, title, message, payload, sent_at, read_at, clicked_at, created_at
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID) (UserNotificationLog, error) {
	row := q.db.QueryRowContext(ctx, markNotificationRead, id)
	var i UserNotificationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EnrollmentID,
		&i.NotificationType,
		&i.Channel,
		&i.Title,
		&i.Message,
		&i.Payload,
		&i.SentAt,
		&i.ReadAt,
		&i.ClickedAt,
		&i.CreatedAt,
	)
	return i, err
}
