// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_enrollments.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cancelEnrollment = `-- name: CancelEnrollment :one
UPDATE user_enrollments
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, trade_id, status, enrolled_at, expires_at, completed_at, progress_pct, metadata, created_at, updated_at
`

func (q *Queries) CancelEnrollment(ctx context.Context, id uuid.UUID) (UserEnrollment, error) {
	row := q.db.QueryRowContext(ctx, cancelEnrollment, id)
	var i UserEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Status,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.ProgressPct,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeEnrollment = `-- name: CompleteEnrollment :one
UPDATE user_enrollments
SET status = 'completed', completed_at = NOW(), progress_pct = 100, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, trade_id, status, enrolled_at, expires_at, completed_at, progress_pct, metadata, created_at, updated_at
`

func (q *Queries) CompleteEnrollment(ctx context.Context, id uuid.UUID) (UserEnrollment, error) {
	row := q.db.QueryRowContext(ctx, completeEnrollment, id)
	var i UserEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Status,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.ProgressPct,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserEnrollment = `-- name: CreateUserEnrollment :one
INSERT INTO user_enrollments (user_id, trade_id, expires_at, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, trade_id, status, enrolled_at, expires_at, completed_at, progress_pct, metadata, created_at, updated_at
`

type CreateUserEnrollmentParams struct {
	UserID    uuid.UUID       `json:"user_id"`
	TradeID   uuid.UUID       `json:"trade_id"`
	ExpiresAt time.Time       `json:"expires_at"`
	Metadata  json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateUserEnrollment(ctx context.Context, arg CreateUserEnrollmentParams) (UserEnrollment, error) {
	row := q.db.QueryRowContext(ctx, createUserEnrollment,
		arg.UserID,
		arg.TradeID,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i UserEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Status,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.ProgressPct,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserEnrollment = `-- name: DeleteUserEnrollment :exec
DELETE FROM user_enrollments WHERE id = $1
`

func (q *Queries) DeleteUserEnrollment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserEnrollment, id)
	return err
}

const getExpiringEnrollments = `-- name: GetExpiringEnrollments :many
SELECT id, user_id, trade_id, status, enrolled_at, expires_at, completed_at, progress_pct, metadata, created_at, updated_at
FROM user_enrollments
WHERE status = 'active'
  AND expires_at <= NOW() + INTERVAL '7 days'
  AND expires_at > NOW()
ORDER BY expires_at ASC
`

func (q *Queries) GetExpiringEnrollments(ctx context.Context) ([]UserEnrollment, error) {
	rows, err := q.db.QueryContext(ctx, getExpiringEnrollments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserEnrollment
	for rows.Next() {
		var i UserEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TradeID,
			&i.Status,
			&i.EnrolledAt,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.ProgressPct,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiringEnrollmentsWithTrade = `-- name: GetExpiringEnrollmentsWithTrade :many
SELECT 
    ue.id, ue.user_id, ue.trade_id, ue.status, ue.enrolled_at, ue.expires_at, ue.completed_at, ue.progress_pct, ue.metadata, ue.created_at, ue.updated_at,
    jt.name as trade_name, jt.slug as trade_slug, jt.category_id,
    jc.name as category_name, jc.slug as category_slug, jc.color as category_color, jc.icon as category_icon
FROM user_enrollments ue
JOIN job_trades jt ON ue.trade_id = jt.id
JOIN job_categories jc ON jt.category_id = jc.id
WHERE ue.status = 'active'
  AND ue.expires_at <= NOW() + INTERVAL '7 days'
  AND ue.expires_at > NOW()
ORDER BY ue.expires_at ASC
`

type GetExpiringEnrollmentsWithTradeRow struct {
	ID            uuid.UUID       `json:"id"`
	UserID        uuid.UUID       `json:"user_id"`
	TradeID       uuid.UUID       `json:"trade_id"`
	Status        string          `json:"status"`
	EnrolledAt    time.Time       `json:"enrolled_at"`
	ExpiresAt     time.Time       `json:"expires_at"`
	CompletedAt   sql.NullTime    `json:"completed_at"`
	ProgressPct   int32           `json:"progress_pct"`
	Metadata      json.RawMessage `json:"metadata"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	TradeName     string          `json:"trade_name"`
	TradeSlug     string          `json:"trade_slug"`
	CategoryID    uuid.UUID       `json:"category_id"`
	CategoryName  string          `json:"category_name"`
	CategorySlug  string          `json:"category_slug"`
	CategoryColor sql.NullString  `json:"category_color"`
	CategoryIcon  sql.NullString  `json:"category_icon"`
}

func (q *Queries) GetExpiringEnrollmentsWithTrade(ctx context.Context) ([]GetExpiringEnrollmentsWithTradeRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiringEnrollmentsWithTrade)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiringEnrollmentsWithTradeRow
	for rows.Next() {
		var i GetExpiringEnrollmentsWithTradeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TradeID,
			&i.Status,
			&i.EnrolledAt,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.ProgressPct,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TradeName,
			&i.TradeSlug,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryColor,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEnrollmentByID = `-- name: GetUserEnrollmentByID :one
SELECT id, user_id, trade_id, status, enrolled_at, expires_at, completed_at, progress_pct, metadata, created_at, updated_at
FROM user_enrollments
WHERE id = $1
`

func (q *Queries) GetUserEnrollmentByID(ctx context.Context, id uuid.UUID) (UserEnrollment, error) {
	row := q.db.QueryRowContext(ctx, getUserEnrollmentByID, id)
	var i UserEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Status,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.ProgressPct,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserEnrollmentByUserAndTrade = `-- name: GetUserEnrollmentByUserAndTrade :one
SELECT id, user_id, trade_id, status, enrolled_at, expires_at, completed_at, progress_pct, metadata, created_at, updated_at
FROM user_enrollments
WHERE user_id = $1 AND trade_id = $2 AND status = 'active'
`

type GetUserEnrollmentByUserAndTradeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	TradeID uuid.UUID `json:"trade_id"`
}

func (q *Queries) GetUserEnrollmentByUserAndTrade(ctx context.Context, arg GetUserEnrollmentByUserAndTradeParams) (UserEnrollment, error) {
	row := q.db.QueryRowContext(ctx, getUserEnrollmentByUserAndTrade, arg.UserID, arg.TradeID)
	var i UserEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Status,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.ProgressPct,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserEnrollments = `-- name: GetUserEnrollments :many
SELECT id, user_id, trade_id, status, enrolled_at, expires_at, completed_at, progress_pct, metadata, created_at, updated_at
FROM user_enrollments
WHERE user_id = $1
  AND ($2::text = '' OR status = $2)
ORDER BY enrolled_at DESC
LIMIT $3 OFFSET $4
`

type GetUserEnrollmentsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetUserEnrollments(ctx context.Context, arg GetUserEnrollmentsParams) ([]UserEnrollment, error) {
	rows, err := q.db.QueryContext(ctx, getUserEnrollments,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserEnrollment
	for rows.Next() {
		var i UserEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TradeID,
			&i.Status,
			&i.EnrolledAt,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.ProgressPct,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEnrollmentsCount = `-- name: GetUserEnrollmentsCount :one
SELECT COUNT(*) FROM user_enrollments
WHERE user_id = $1
  AND ($2::text = '' OR status = $2)
`

type GetUserEnrollmentsCountParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) GetUserEnrollmentsCount(ctx context.Context, arg GetUserEnrollmentsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserEnrollmentsCount, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateEnrollmentProgress = `-- name: UpdateEnrollmentProgress :one
UPDATE user_enrollments
SET progress_pct = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, trade_id, status, enrolled_at, expires_at, completed_at, progress_pct, metadata, created_at, updated_at
`

type UpdateEnrollmentProgressParams struct {
	ID          uuid.UUID `json:"id"`
	ProgressPct int32     `json:"progress_pct"`
}

func (q *Queries) UpdateEnrollmentProgress(ctx context.Context, arg UpdateEnrollmentProgressParams) (UserEnrollment, error) {
	row := q.db.QueryRowContext(ctx, updateEnrollmentProgress, arg.ID, arg.ProgressPct)
	var i UserEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Status,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.ProgressPct,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEnrollment = `-- name: UpdateUserEnrollment :one
UPDATE user_enrollments
SET status = $2, expires_at = COALESCE($3, expires_at), completed_at = $4, progress_pct = $5, metadata = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, trade_id, status, enrolled_at, expires_at, completed_at, progress_pct, metadata, created_at, updated_at
`

type UpdateUserEnrollmentParams struct {
	ID          uuid.UUID       `json:"id"`
	Status      string          `json:"status"`
	ExpiresAt   time.Time       `json:"expires_at"`
	CompletedAt sql.NullTime    `json:"completed_at"`
	ProgressPct int32           `json:"progress_pct"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateUserEnrollment(ctx context.Context, arg UpdateUserEnrollmentParams) (UserEnrollment, error) {
	row := q.db.QueryRowContext(ctx, updateUserEnrollment,
		arg.ID,
		arg.Status,
		arg.ExpiresAt,
		arg.CompletedAt,
		arg.ProgressPct,
		arg.Metadata,
	)
	var i UserEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TradeID,
		&i.Status,
		&i.EnrolledAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.ProgressPct,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
