apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/kustomization.yaml
commonLabels:
  region: apac
patchesStrategicMerge:
- patch-region.yaml
- patch-db.yaml
- patch-ingress.yaml
images:
- name: backend
  newTag: v2.0-apac
- name: crawler
  newTag: v2.0-apac
