// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

// @title Rojgarsetu API
// @version 2.0.0
// @description Rojgarsetu - Government and Private Job Portal API
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.rojgarsetu.com/support
// @contact.email support@rojgarsetu.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8083
// @BasePath /api/v1
// @schemes http https

// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

// @tag.name jobs
// @tag.description Job listings and management

// @tag.name search
// @tag.description Full-text search functionality

// @tag.name auth
// @tag.description Authentication and authorization

// @tag.name crawler
// @tag.description Job crawling and data ingestion
