// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candidates.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const createCandidate = `-- name: CreateCandidate :one
INSERT INTO candidates (
  user_id, phone, resume_url, resume_parsed, skills, experience_years,
  current_company, current_position, location, linkedin_url, github_url,
  portfolio_url, bio, is_open_to_work, expected_salary, preferred_job_type,
  preferred_location
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
) RETURNING id, user_id, phone, resume_url, resume_parsed, skills, experience_years, current_company, current_position, location, linkedin_url, github_url, portfolio_url, bio, is_open_to_work, expected_salary, preferred_job_type, preferred_location, created_at, updated_at
`

type CreateCandidateParams struct {
	UserID            uuid.UUID             `json:"user_id"`
	Phone             sql.NullString        `json:"phone"`
	ResumeUrl         sql.NullString        `json:"resume_url"`
	ResumeParsed      pqtype.NullRawMessage `json:"resume_parsed"`
	Skills            []string              `json:"skills"`
	ExperienceYears   sql.NullInt32         `json:"experience_years"`
	CurrentCompany    sql.NullString        `json:"current_company"`
	CurrentPosition   sql.NullString        `json:"current_position"`
	Location          sql.NullString        `json:"location"`
	LinkedinUrl       sql.NullString        `json:"linkedin_url"`
	GithubUrl         sql.NullString        `json:"github_url"`
	PortfolioUrl      sql.NullString        `json:"portfolio_url"`
	Bio               sql.NullString        `json:"bio"`
	IsOpenToWork      sql.NullBool          `json:"is_open_to_work"`
	ExpectedSalary    sql.NullString        `json:"expected_salary"`
	PreferredJobType  []string              `json:"preferred_job_type"`
	PreferredLocation []string              `json:"preferred_location"`
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, createCandidate,
		arg.UserID,
		arg.Phone,
		arg.ResumeUrl,
		arg.ResumeParsed,
		pq.Array(arg.Skills),
		arg.ExperienceYears,
		arg.CurrentCompany,
		arg.CurrentPosition,
		arg.Location,
		arg.LinkedinUrl,
		arg.GithubUrl,
		arg.PortfolioUrl,
		arg.Bio,
		arg.IsOpenToWork,
		arg.ExpectedSalary,
		pq.Array(arg.PreferredJobType),
		pq.Array(arg.PreferredLocation),
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.ResumeUrl,
		&i.ResumeParsed,
		pq.Array(&i.Skills),
		&i.ExperienceYears,
		&i.CurrentCompany,
		&i.CurrentPosition,
		&i.Location,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.Bio,
		&i.IsOpenToWork,
		&i.ExpectedSalary,
		pq.Array(&i.PreferredJobType),
		pq.Array(&i.PreferredLocation),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandidateByID = `-- name: GetCandidateByID :one
SELECT id, user_id, phone, resume_url, resume_parsed, skills, experience_years, current_company, current_position, location, linkedin_url, github_url, portfolio_url, bio, is_open_to_work, expected_salary, preferred_job_type, preferred_location, created_at, updated_at FROM candidates WHERE id = $1
`

func (q *Queries) GetCandidateByID(ctx context.Context, id uuid.UUID) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getCandidateByID, id)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.ResumeUrl,
		&i.ResumeParsed,
		pq.Array(&i.Skills),
		&i.ExperienceYears,
		&i.CurrentCompany,
		&i.CurrentPosition,
		&i.Location,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.Bio,
		&i.IsOpenToWork,
		&i.ExpectedSalary,
		pq.Array(&i.PreferredJobType),
		pq.Array(&i.PreferredLocation),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandidateByUserID = `-- name: GetCandidateByUserID :one
SELECT id, user_id, phone, resume_url, resume_parsed, skills, experience_years, current_company, current_position, location, linkedin_url, github_url, portfolio_url, bio, is_open_to_work, expected_salary, preferred_job_type, preferred_location, created_at, updated_at FROM candidates WHERE user_id = $1
`

func (q *Queries) GetCandidateByUserID(ctx context.Context, userID uuid.UUID) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getCandidateByUserID, userID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.ResumeUrl,
		&i.ResumeParsed,
		pq.Array(&i.Skills),
		&i.ExperienceYears,
		&i.CurrentCompany,
		&i.CurrentPosition,
		&i.Location,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.Bio,
		&i.IsOpenToWork,
		&i.ExpectedSalary,
		pq.Array(&i.PreferredJobType),
		pq.Array(&i.PreferredLocation),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandidatesCount = `-- name: GetCandidatesCount :one
SELECT COUNT(*) FROM candidates WHERE is_active = true
  AND ($1::text = '' OR location ILIKE '%' || $1 || '%')
`

func (q *Queries) GetCandidatesCount(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCandidatesCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCandidates = `-- name: ListCandidates :many
SELECT id, user_id, phone, resume_url, resume_parsed, skills, experience_years, current_company, current_position, location, linkedin_url, github_url, portfolio_url, bio, is_open_to_work, expected_salary, preferred_job_type, preferred_location, created_at, updated_at FROM candidates WHERE is_active = true
  AND ($1::text = '' OR location ILIKE '%' || $1 || '%')
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCandidatesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]Candidate, error) {
	rows, err := q.db.QueryContext(ctx, listCandidates, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candidate
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Phone,
			&i.ResumeUrl,
			&i.ResumeParsed,
			pq.Array(&i.Skills),
			&i.ExperienceYears,
			&i.CurrentCompany,
			&i.CurrentPosition,
			&i.Location,
			&i.LinkedinUrl,
			&i.GithubUrl,
			&i.PortfolioUrl,
			&i.Bio,
			&i.IsOpenToWork,
			&i.ExpectedSalary,
			pq.Array(&i.PreferredJobType),
			pq.Array(&i.PreferredLocation),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCandidate = `-- name: UpdateCandidate :one
UPDATE candidates SET 
  phone = $2, resume_url = $3, skills = $4, experience_years = $5,
  current_company = $6, current_position = $7, location = $8,
  linkedin_url = $9, github_url = $10, portfolio_url = $11, bio = $12,
  is_open_to_work = $13, expected_salary = $14, preferred_job_type = $15,
  preferred_location = $16, updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, phone, resume_url, resume_parsed, skills, experience_years, current_company, current_position, location, linkedin_url, github_url, portfolio_url, bio, is_open_to_work, expected_salary, preferred_job_type, preferred_location, created_at, updated_at
`

type UpdateCandidateParams struct {
	ID                uuid.UUID      `json:"id"`
	Phone             sql.NullString `json:"phone"`
	ResumeUrl         sql.NullString `json:"resume_url"`
	Skills            []string       `json:"skills"`
	ExperienceYears   sql.NullInt32  `json:"experience_years"`
	CurrentCompany    sql.NullString `json:"current_company"`
	CurrentPosition   sql.NullString `json:"current_position"`
	Location          sql.NullString `json:"location"`
	LinkedinUrl       sql.NullString `json:"linkedin_url"`
	GithubUrl         sql.NullString `json:"github_url"`
	PortfolioUrl      sql.NullString `json:"portfolio_url"`
	Bio               sql.NullString `json:"bio"`
	IsOpenToWork      sql.NullBool   `json:"is_open_to_work"`
	ExpectedSalary    sql.NullString `json:"expected_salary"`
	PreferredJobType  []string       `json:"preferred_job_type"`
	PreferredLocation []string       `json:"preferred_location"`
}

func (q *Queries) UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, updateCandidate,
		arg.ID,
		arg.Phone,
		arg.ResumeUrl,
		pq.Array(arg.Skills),
		arg.ExperienceYears,
		arg.CurrentCompany,
		arg.CurrentPosition,
		arg.Location,
		arg.LinkedinUrl,
		arg.GithubUrl,
		arg.PortfolioUrl,
		arg.Bio,
		arg.IsOpenToWork,
		arg.ExpectedSalary,
		pq.Array(arg.PreferredJobType),
		pq.Array(arg.PreferredLocation),
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.ResumeUrl,
		&i.ResumeParsed,
		pq.Array(&i.Skills),
		&i.ExperienceYears,
		&i.CurrentCompany,
		&i.CurrentPosition,
		&i.Location,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.Bio,
		&i.IsOpenToWork,
		&i.ExpectedSalary,
		pq.Array(&i.PreferredJobType),
		pq.Array(&i.PreferredLocation),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
