// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, provider, title, url, duration, mode, level, skills,
       description, thumbnail_url, price, is_free, source, created_at
FROM courses 
WHERE id = $1 AND is_active = true
`

type GetCourseByIDRow struct {
	ID           uuid.UUID      `json:"id"`
	Provider     string         `json:"provider"`
	Title        string         `json:"title"`
	Url          string         `json:"url"`
	Duration     sql.NullString `json:"duration"`
	Mode         sql.NullString `json:"mode"`
	Level        sql.NullString `json:"level"`
	Skills       []string       `json:"skills"`
	Description  sql.NullString `json:"description"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	Price        sql.NullString `json:"price"`
	IsFree       sql.NullBool   `json:"is_free"`
	Source       string         `json:"source"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetCourseByID(ctx context.Context, id uuid.UUID) (GetCourseByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseByID, id)
	var i GetCourseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Title,
		&i.Url,
		&i.Duration,
		&i.Mode,
		&i.Level,
		pq.Array(&i.Skills),
		&i.Description,
		&i.ThumbnailUrl,
		&i.Price,
		&i.IsFree,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT id, provider, title, url, duration, mode, level, skills,
       description, thumbnail_url, price, is_free, source, created_at
FROM courses 
WHERE is_active = true
  AND ($1::text = '' OR provider ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR mode = $2)
  AND ($3::text = '' OR level = $3)
ORDER BY created_at DESC 
LIMIT $4 OFFSET $5
`

type GetCoursesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetCoursesRow struct {
	ID           uuid.UUID      `json:"id"`
	Provider     string         `json:"provider"`
	Title        string         `json:"title"`
	Url          string         `json:"url"`
	Duration     sql.NullString `json:"duration"`
	Mode         sql.NullString `json:"mode"`
	Level        sql.NullString `json:"level"`
	Skills       []string       `json:"skills"`
	Description  sql.NullString `json:"description"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	Price        sql.NullString `json:"price"`
	IsFree       sql.NullBool   `json:"is_free"`
	Source       string         `json:"source"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetCourses(ctx context.Context, arg GetCoursesParams) ([]GetCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCourses,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesRow
	for rows.Next() {
		var i GetCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Title,
			&i.Url,
			&i.Duration,
			&i.Mode,
			&i.Level,
			pq.Array(&i.Skills),
			&i.Description,
			&i.ThumbnailUrl,
			&i.Price,
			&i.IsFree,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesCount = `-- name: GetCoursesCount :one
SELECT COUNT(*) FROM courses WHERE is_active = true
  AND ($1::text = '' OR provider ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR mode = $2)
  AND ($3::text = '' OR level = $3)
`

type GetCoursesCountParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) GetCoursesCount(ctx context.Context, arg GetCoursesCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCoursesCount, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}
