// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: priv_jobs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getPrivJobByID = `-- name: GetPrivJobByID :one
SELECT id, company, title, location, url, salary, experience, 
       job_type, skills, description, source, posted_at, created_at
FROM jobs_private 
WHERE id = $1 AND is_active = true
`

type GetPrivJobByIDRow struct {
	ID          uuid.UUID      `json:"id"`
	Company     string         `json:"company"`
	Title       string         `json:"title"`
	Location    sql.NullString `json:"location"`
	Url         sql.NullString `json:"url"`
	Salary      sql.NullString `json:"salary"`
	Experience  sql.NullString `json:"experience"`
	JobType     sql.NullString `json:"job_type"`
	Skills      []string       `json:"skills"`
	Description sql.NullString `json:"description"`
	Source      string         `json:"source"`
	PostedAt    sql.NullTime   `json:"posted_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetPrivJobByID(ctx context.Context, id uuid.UUID) (GetPrivJobByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPrivJobByID, id)
	var i GetPrivJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Title,
		&i.Location,
		&i.Url,
		&i.Salary,
		&i.Experience,
		&i.JobType,
		pq.Array(&i.Skills),
		&i.Description,
		&i.Source,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPrivJobs = `-- name: GetPrivJobs :many
SELECT id, company, title, location, url, salary, experience, 
       job_type, skills, description, source, posted_at, created_at
FROM jobs_private 
WHERE is_active = true
  AND ($1::text = '' OR company ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR location ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR source = $3)
  AND ($4::text = '' OR job_type = $4)
ORDER BY created_at DESC 
LIMIT $5 OFFSET $6
`

type GetPrivJobsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetPrivJobsRow struct {
	ID          uuid.UUID      `json:"id"`
	Company     string         `json:"company"`
	Title       string         `json:"title"`
	Location    sql.NullString `json:"location"`
	Url         sql.NullString `json:"url"`
	Salary      sql.NullString `json:"salary"`
	Experience  sql.NullString `json:"experience"`
	JobType     sql.NullString `json:"job_type"`
	Skills      []string       `json:"skills"`
	Description sql.NullString `json:"description"`
	Source      string         `json:"source"`
	PostedAt    sql.NullTime   `json:"posted_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetPrivJobs(ctx context.Context, arg GetPrivJobsParams) ([]GetPrivJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPrivJobs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrivJobsRow
	for rows.Next() {
		var i GetPrivJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.Salary,
			&i.Experience,
			&i.JobType,
			pq.Array(&i.Skills),
			&i.Description,
			&i.Source,
			&i.PostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrivJobsCount = `-- name: GetPrivJobsCount :one
SELECT COUNT(*) FROM jobs_private WHERE is_active = true
  AND ($1::text = '' OR company ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR location ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR source = $3)
  AND ($4::text = '' OR job_type = $4)
`

type GetPrivJobsCountParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

func (q *Queries) GetPrivJobsCount(ctx context.Context, arg GetPrivJobsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPrivJobsCount,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
