apiVersion: apps/v1
$patch: replace
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: CRAWLER_REGION
          value: "apac"
        - name: DB_URL_LOCAL
          valueFrom:
            secretKeyRef:
              name: rojgarsetu-secrets-apac
              key: ro_database_url
---
apiVersion: apps/v1
$patch: replace
kind: Deployment
metadata:
  name: crawler
spec:
  template:
    spec:
      containers:
      - name: crawler
        env:
        - name: CRAWLER_REGION
          value: "apac"
---
apiVersion: networking.k8s.io/v1
$patch: replace
kind: Ingress
metadata:
  name: rojgarsetu-ingress
spec:
  rules:
  - host: apac.rojgarsetu.com
  tls:
  - hosts:
    - apac.rojgarsetu.com
    secretName: apac-rojgarsetu-tls
