apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/kustomization.yaml
commonLabels:
  region: eu
patchesStrategicMerge:
- patch-region.yaml
- patch-db.yaml
- patch-ingress.yaml
images:
- name: backend
  newTag: v2.0-eu
- name: crawler
  newTag: v2.0-eu
nodeSelector:
  topology.kubernetes.io/region: europe-west1
